DECLARE

    V_INDEX   VARCHAR2(256);
    V_SQL     VARCHAR2(1000);
   
    CURSOR C_INDEXES IS        
        SELECT index_name  
        FROM all_indexes 
        WHERE table_owner = 'RENDIMPC'
        AND tablespace_name = 'TBS_RENDIMPC_IDX_TEMP';
        
BEGIN

OPEN C_INDEXES;

    LOOP
	    BEGIN
			FETCH C_INDEXES INTO V_INDEX;

			EXIT WHEN C_INDEXES%NOTFOUND;
			V_SQL := 'DROP INDEX RENDIMPC.' || V_INDEX ;
			
			EXECUTE IMMEDIATE V_SQL;
		
		END;
    END LOOP;

    CLOSE C_INDEXES;

    V_SQL := 'PURGE RECYCLEBIN';
    
    EXECUTE IMMEDIATE V_SQL;
    
    
	INSERT INTO OUTPUT_PRINT_TABLE VALUES (TO_NUMBER(TO_CHAR(SYSDATE,'YYYYMMDDHH24MISS')) || ' DROPPATI TUTTI GLI INDICI APPESI!');
    
    COMMIT;
END;

