DECLARE 

    rowcounts NUMBER;

BEGIN
   
MERGE INTO MOVIMENTO MOV
USING (SELECT  	R.ID AS IDRAPPORTO, 
		        'MOVIMP-'||TMP.CODICERAPPORTO||'-'||TMP.CODICEINTERNO||'-20171231' AS numreg,
                case when R.TIPO = '02' then 'LIQ_EUR_LIB'
                    else TMP.CODICEINTERNO end as codicetitolo,
                R.TIPO || '_MOVIMP' AS CAUSALE,
		        '20171231' AS DATAVALUTA,
		        NULL AS DATACONT,
		        NULL AS CAMBIO,
              case when R.TIPO = '02' then TMP.CONTROVALORE_VINCOLATO 
                    else TMP.CONTROVALORE end as CTV,		      
              case when R.TIPO = '02' then null  
                    else TMP.CONTROVALORE end AS CTVDIVISA,                   
		        NULL AS CTVNETTO,
		      case when R.TIPO = '02' then TMP.CONTROVALORE_VINCOLATO
		         else TMP.Quantita end as Quantita,
		        'EUR' as DIVISA,
		        TO_NUMBER(TO_CHAR(SYSDATE,'YYYYMMDD')) as D_AGGIORNAMENTO,
		        'PDR' as C_PROCEDURA,
		        'MOVIMP' as CAUSALE_ORI
		FROM TMP_PFSALDI_MOVIMP TMP
		INNER JOIN RAPPORTO R
		    ON TMP.CODICERAPPORTO = R.CODICERAPPORTO
		WHERE R.TIPO IN ('14','15')
            OR (R.TIPO = '02' AND TMP.CONTROVALORE_VINCOLATO is not null)
		) TOMERGE
	ON (MOV.IDRAPPORTO = TOMERGE.IDRAPPORTO
	   AND MOV.NUMREG = TOMERGE.numreg)
WHEN MATCHED THEN
 UPDATE SET MOV.CODICETITOLO 	= TOMERGE.CODICETITOLO,
   		MOV.CAUSALE 		= TOMERGE.CAUSALE, 
   		MOV.DATA	 		= TOMERGE.DATAVALUTA,
   		MOV.DATACONT 		= TOMERGE.DATACONT,
   		MOV.CAMBIO 			= TOMERGE.CAMBIO,
   		MOV.CTV 			= TOMERGE.CTV,
   		MOV.CTVDIVISA 		= TOMERGE.CTVDIVISA,
        MOV.CTVNETTO        = TOMERGE.CTVNETTO,
        MOV.QTA				= TOMERGE.Quantita,
        MOV.DIVISA			= TOMERGE.DIVISA,
        MOV.VALUTA			= TOMERGE.DATAVALUTA,
        MOV.causale_ori		= TOMERGE.CAUSALE_ORI,
        MOV.D_AGGIORNAMENTO = TOMERGE.D_AGGIORNAMENTO,
        MOV.C_PROCEDURA		= TOMERGE.C_PROCEDURA
        
WHEN NOT MATCHED THEN
INSERT (IDRAPPORTO,
		NUMREG,
		CODICETITOLO,
		CAUSALE,
		DATA,
		DATACONT,
		CAMBIO,
		CTV,
		CTVDIVISA,
        CTVNETTO,
        QTA,
        DIVISA,
        VALUTA,
        CAUSALE_ORI, 
        D_AGGIORNAMENTO, 
        C_PROCEDURA
        ) 
VALUES (TOMERGE.IDRAPPORTO,
		TOMERGE.NUMREG,
		TOMERGE.CODICETITOLO,
		TOMERGE.CAUSALE,
		TOMERGE.DATAVALUTA,
		TOMERGE.DATACONT,
		TOMERGE.CAMBIO,
		TOMERGE.CTV,
		TOMERGE.CTVDIVISA,
        TOMERGE.CTVNETTO,
        TOMERGE.QUANTITA,
        TOMERGE.DIVISA,
        TOMERGE.DATAVALUTA,
        TOMERGE.CAUSALE_ORI,
        TOMERGE.D_AGGIORNAMENTO,
        TOMERGE.C_PROCEDURA
        );
        
        rowcounts := SQL%ROWCOUNT;
		
INSERT INTO output_print_table VALUES (to_number(to_char(sysdate,'YYYYMMDDHH24MISS')) || ' MERGE MOVIMENTI IMPIANTO TIPI 02,14,15: ' || rowcounts);
	COMMIT;

END;