DECLARE 

    rowcounts NUMBER;

    
BEGIN
   
MERGE INTO
    SERIE_STORICA SER
  USING (
          SELECT
            TCAMBI.CODICEDIVISAINCERTO       											AS CODICETITOLO,
            'C'                             											AS TIPO,
            TO_NUMBER(TO_CHAR(TO_DATE(TCAMBI.DATACAMBIO, 'YYYY-MM-DD'), 'YYYYMMDD'))	AS DATALIVELLO,
            TCAMBI.CAMBIO         			 											AS VALORE,
            TCAMBI.CODICEDIVISACERTO         											AS DIVISA,
            TO_DATE(TCAMBI.DATAAGGIORNAMENTO, 'YYYY-MM-DD HH24:MI:SS')					AS DATA_AGGIORNAMENTO,
            TCAMBI.CAMBIO         			 											AS VALORE_LORDO
          FROM
            TMP_PFCAMBI TCAMBI) TOMERGE
  ON
  (SER.DIVISA = TOMERGE.DIVISA
   AND SER.CODICETITOLO = TOMERGE.CODICETITOLO
   AND SER.DATALIVELLO = TOMERGE.DATALIVELLO
  )
  WHEN MATCHED THEN
  UPDATE
  SET
  	SER.TIPO = TOMERGE.TIPO,
    SER.VALORE = TOMERGE.VALORE,
    SER.VALORE_LORDO = TOMERGE.VALORE_LORDO,
    SER.DATA_AGGIORNAMENTO = TOMERGE.DATA_AGGIORNAMENTO
    
  WHEN NOT MATCHED THEN
  INSERT( 	CODICETITOLO, 
		    TIPO, 
		    DATALIVELLO, 
		    VALORE, 
		    DIVISA, 
		    VALORE_LORDO, 
		    DATA_AGGIORNAMENTO)
  VALUES (
    TOMERGE.CODICETITOLO,
    TOMERGE.TIPO,
    TOMERGE.DATALIVELLO,
    TOMERGE.VALORE,
    TOMERGE.DIVISA,
    TOMERGE.VALORE_LORDO,
    TOMERGE.DATA_AGGIORNAMENTO
  );
  
   rowcounts := SQL%ROWCOUNT;
  
INSERT INTO output_print_table VALUES (to_number(to_char(sysdate,'YYYYMMDDHH24MISS')) || ' MERGE CAMBI IN SERIE_STORICA: ' || rowcounts);
	COMMIT;

END;