CREATE OR REPLACE FUNCTION PARALLEL_MOVIMENTI (
	MOVIMENTI IN SYS_REFCURSOR
) 
RETURN PARALLEL_FUNCTION
PARALLEL_ENABLE (PARTITION MOVIMENTI BY ANY)
PIPELINED
IS
        PRAGMA AUTONOMOUS_TRANSACTION;
    
     TYPE MOVIMENTI_TYPE_CUR IS RECORD (
        							
	 IDRAPPORTO					NUMBER,
     NUMREG						VARCHAR2(256),
     CAMBIO						FLOAT(126),
     CAUSALE					VARCHAR2(256),
     CODICETITOLO				VARCHAR2(256),
     CTV						FLOAT(126),
     CTVORIG					FLOAT(126),
     CTVDIVISA					FLOAT(126),
     CTVNETTO					FLOAT(126),
     DATA						NUMBER,
     DATACONT					NUMBER,
     DIVISA						VARCHAR2(256),
     FLAGPCT					VARCHAR2(3),
     PREZZO						FLOAT(126),
     QTA						FLOAT(126),
     RATEOLORDO					FLOAT(126),
     RATEONETTO					FLOAT(126),
     SPESECOMM					FLOAT(126),
     TASSAZIONE					FLOAT(126),
     VALUTA						NUMBER,
     STORNO						VARCHAR2(3),
     CTV_MERCATO				FLOAT(126),
     CTV_MERCATO_DIVISA			FLOAT(126),
     DATA_REGISTRAZIONE			NUMBER,
     DATA_SOTTOSCRIZIONE		NUMBER,
     PREZZO_MERCATO				FLOAT(126),
     N_OPERAZIONE_STORNO		VARCHAR2(256),
     F_CANCELLATO				VARCHAR2(256),
     C_CANALE					VARCHAR2(256),
     Z_CANALE					VARCHAR2(256),
     QTA_CAPITALE				FLOAT(126),
     PROVENIENZACAUSALE			VARCHAR2(256),
     D_AGGIORNAMENTO			NUMBER,
     C_PROCEDURA				VARCHAR2(256),
     BANCA_DA					VARCHAR2(256),
     CODICEAGENZIA_DA			VARCHAR2(256),	
     CODICERAPPORTO_DA			VARCHAR2(256),
     BANCA_A					VARCHAR2(256),
     CODICEAGENZIA_A			VARCHAR2(256),
     CODICERAPPORTO_A			VARCHAR2(256),
     CODICEFILIALE				VARCHAR2(256),
     CODICERAPPORTO_ORI			VARCHAR2(256),
     CAUSALE_ORI				VARCHAR2(256),
     FONTE						VARCHAR2(5),
     IMPOSTA_REST				FLOAT(126)
     
);
    
    
    
TYPE MOVIMENTI_TYPE IS TABLE OF MOVIMENTI_TYPE_CUR;

RES_MOVIMENTI MOVIMENTI_TYPE;
	
ROWS    PLS_INTEGER := 10000;	
I 		NUMBER(38,0):=0;


			
BEGIN
							
		LOOP
			FETCH movimenti BULK COLLECT INTO RES_movimenti LIMIT ROWS;
             	EXIT WHEN RES_movimenti.COUNT = 0;  
			
			I:=0;
			I:= RES_movimenti.COUNT;
				
			FORALL J IN RES_movimenti.FIRST .. RES_movimenti.LAST	
			
				MERGE INTO
					 MOVIMENTO MOV
						USING (
								SELECT
									RES_MOVIMENTI(J).IDRAPPORTO AS IDRAPPORTO,
									RES_MOVIMENTI(J).NUMREG AS NUMREG,
									RES_MOVIMENTI(J).CAMBIO AS CAMBIO,
									RES_MOVIMENTI(J).CAUSALE AS CAUSALE,
									RES_MOVIMENTI(J).CODICETITOLO AS CODICETITOLO,
									RES_MOVIMENTI(J).CTV AS CTV,
									RES_MOVIMENTI(J).CTVORIG AS CTVORIG,
									RES_MOVIMENTI(J).CTVDIVISA AS CTVDIVISA,
									RES_MOVIMENTI(J).CTVNETTO AS CTVNETTO,
									RES_MOVIMENTI(J).DATA AS DATA,
									RES_MOVIMENTI(J).DATACONT AS DATACONT,
									RES_MOVIMENTI(J).DIVISA AS DIVISA,
									RES_MOVIMENTI(J).FLAGPCT AS FLAGPCT,
									RES_MOVIMENTI(J).PREZZO AS PREZZO,
									RES_MOVIMENTI(J).QTA AS QTA,
									RES_MOVIMENTI(J).RATEOLORDO AS RATEOLORDO,
									RES_MOVIMENTI(J).RATEONETTO AS RATEONETTO,
									RES_MOVIMENTI(J).SPESECOMM AS SPESECOMM,
									RES_MOVIMENTI(J).TASSAZIONE AS TASSAZIONE,
									RES_MOVIMENTI(J).VALUTA AS VALUTA,
									RES_MOVIMENTI(J).STORNO AS STORNO,
									RES_MOVIMENTI(J).CTV_MERCATO AS CTV_MERCATO,
									RES_MOVIMENTI(J).CTV_MERCATO_DIVISA AS CTV_MERCATO_DIVISA,
									RES_MOVIMENTI(J).DATA_REGISTRAZIONE AS DATA_REGISTRAZIONE,
									RES_MOVIMENTI(J).DATA_SOTTOSCRIZIONE AS DATA_SOTTOSCRIZIONE,
									RES_MOVIMENTI(J).PREZZO_MERCATO AS PREZZO_MERCATO,
									RES_MOVIMENTI(J).N_OPERAZIONE_STORNO AS N_OPERAZIONE_STORNO,
									RES_MOVIMENTI(J).F_CANCELLATO AS F_CANCELLATO,
									RES_MOVIMENTI(J).C_CANALE AS C_CANALE,
									RES_MOVIMENTI(J).Z_CANALE AS Z_CANALE,
									RES_MOVIMENTI(J).QTA_CAPITALE AS QTA_CAPITALE,
									RES_MOVIMENTI(J).PROVENIENZACAUSALE AS PROVENIENZACAUSALE,
									RES_MOVIMENTI(J).D_AGGIORNAMENTO AS D_AGGIORNAMENTO,
									RES_MOVIMENTI(J).C_PROCEDURA AS C_PROCEDURA,
									RES_MOVIMENTI(J).BANCA_DA AS BANCA_DA,
									RES_MOVIMENTI(J).CODICEAGENZIA_DA AS CODICEAGENZIA_DA,
									RES_MOVIMENTI(J).CODICERAPPORTO_DA AS CODICERAPPORTO_DA,
									RES_MOVIMENTI(J).BANCA_A AS BANCA_A,
									RES_MOVIMENTI(J).CODICEAGENZIA_A AS CODICEAGENZIA_A,
									RES_MOVIMENTI(J).CODICERAPPORTO_A AS CODICERAPPORTO_A,
									RES_MOVIMENTI(J).CODICEFILIALE AS CODICEFILIALE,
									RES_MOVIMENTI(J).CODICERAPPORTO_ORI AS CODICERAPPORTO_ORI,
									RES_MOVIMENTI(J).CAUSALE_ORI AS CAUSALE_ORI,
									RES_MOVIMENTI(J).FONTE AS FONTE,
									RES_MOVIMENTI(J).IMPOSTA_REST AS IMPOSTA_REST
								FROM dual
								) TOMERGE
						 ON (MOV.IDRAPPORTO = TOMERGE.IDRAPPORTO
						   AND MOV.NUMREG = TOMERGE.NUMREG)
						   
						  WHEN MATCHED THEN UPDATE
						  SET
						    MOV.CAMBIO = TOMERGE.CAMBIO,
						    MOV.CAUSALE = TOMERGE.CAUSALE,
						    MOV.CODICETITOLO = TOMERGE.CODICETITOLO,
						    MOV.CTV = TOMERGE.CTV,
						    MOV.CTVORIG = TOMERGE.CTVORIG,
						    MOV.CTVDIVISA = TOMERGE.CTVDIVISA,
						    MOV.CTVNETTO = TOMERGE.CTVNETTO,
						    MOV."DATA" = TOMERGE."DATA",
						    MOV.DATACONT = TOMERGE.DATACONT,
						    MOV.DIVISA = TOMERGE.DIVISA,
						    MOV.FLAGPCT = TOMERGE.FLAGPCT,
						    MOV.PREZZO = TOMERGE.PREZZO,
						    MOV.QTA = TOMERGE.QTA,
						    MOV.RATEOLORDO = TOMERGE.RATEOLORDO,
						    MOV.RATEONETTO = TOMERGE.RATEONETTO,
						    MOV.SPESECOMM = TOMERGE.SPESECOMM,
						    MOV.TASSAZIONE = TOMERGE.TASSAZIONE,
						    MOV.VALUTA = TOMERGE.VALUTA,
						    MOV.STORNO = TOMERGE.STORNO,
						    MOV.CTV_MERCATO = TOMERGE.CTV_MERCATO,
						    MOV.CTV_MERCATO_DIVISA = TOMERGE.CTV_MERCATO_DIVISA,
						    MOV.DATA_REGISTRAZIONE = TOMERGE.DATA_REGISTRAZIONE,
						    MOV.DATA_SOTTOSCRIZIONE = TOMERGE.DATA_SOTTOSCRIZIONE,
						    MOV.PREZZO_MERCATO = TOMERGE.PREZZO_MERCATO,
						    MOV.N_OPERAZIONE_STORNO = TOMERGE.N_OPERAZIONE_STORNO,
						    MOV.F_CANCELLATO = TOMERGE.F_CANCELLATO,
						    MOV.C_CANALE = TOMERGE.C_CANALE,
						    MOV.Z_CANALE = TOMERGE.Z_CANALE,
						    MOV.QTA_CAPITALE = TOMERGE.QTA_CAPITALE,
						    MOV.PROVENIENZACAUSALE = TOMERGE.PROVENIENZACAUSALE,
						    MOV.D_AGGIORNAMENTO = TOMERGE.D_AGGIORNAMENTO,
						    MOV.C_PROCEDURA = TOMERGE.C_PROCEDURA,
						    MOV.BANCA_DA = TOMERGE.BANCA_DA,
						    MOV.CODICEAGENZIA_DA = TOMERGE.CODICEAGENZIA_DA,
						    MOV.CODICERAPPORTO_DA = TOMERGE.CODICERAPPORTO_DA,
						    MOV.BANCA_A = TOMERGE.BANCA_A,
						    MOV.CODICEAGENZIA_A = TOMERGE.CODICEAGENZIA_A,
						    MOV.CODICERAPPORTO_A = TOMERGE.CODICERAPPORTO_A,
						    MOV.CODICERAPPORTO_ORI = TOMERGE.CODICERAPPORTO_ORI,
						    MOV.CAUSALE_ORI = TOMERGE.CAUSALE_ORI,
						    MOV.FONTE = TOMERGE.FONTE,
						    MOV.IMPOSTA_REST = TOMERGE.IMPOSTA_REST
						  
						    WHEN NOT MATCHED THEN 
						  	INSERT
						    (IDRAPPORTO,
						     NUMREG,
						     CAMBIO,
						     CAUSALE,
						     CODICETITOLO,
						     CTV,
						     CTVORIG,
						     CTVDIVISA,
						     CTVNETTO,
						     DATA,
						     DATACONT,
						     DIVISA,
						     FLAGPCT,
						     PREZZO,
						     QTA,
						     RATEOLORDO,
						     RATEONETTO,
						     SPESECOMM,
						     TASSAZIONE,
						     VALUTA,
						     STORNO,
						     CTV_MERCATO,
						     CTV_MERCATO_DIVISA,
						     DATA_REGISTRAZIONE,
						     DATA_SOTTOSCRIZIONE,
						     PREZZO_MERCATO,
						     N_OPERAZIONE_STORNO,
						     F_CANCELLATO,
						     C_CANALE,
						     Z_CANALE,
						     QTA_CAPITALE,
						     PROVENIENZACAUSALE,
						     D_AGGIORNAMENTO,
						     C_PROCEDURA,
						     BANCA_DA,
						     CODICEAGENZIA_DA,
						     CODICERAPPORTO_DA,
						     BANCA_A,
						     CODICEAGENZIA_A,
						     CODICERAPPORTO_A,
						     CODICERAPPORTO_ORI,
						     CAUSALE_ORI,
						     FONTE,
						     IMPOSTA_REST
						  )
						  VALUES (TOMERGE.IDRAPPORTO,
						    TOMERGE.NUMREG,
						    TOMERGE.CAMBIO,
						    TOMERGE.CAUSALE,
						    TOMERGE.CODICETITOLO,
						    TOMERGE.CTV,
						    TOMERGE.CTVORIG,
						    TOMERGE.CTVDIVISA,
						    TOMERGE.CTVNETTO,
						    TOMERGE.DATA,
						    TOMERGE.DATACONT,
						    TOMERGE.DIVISA,
						    TOMERGE.FLAGPCT,
						    TOMERGE.PREZZO,
						    TOMERGE.QTA,
						    TOMERGE.RATEOLORDO,
						    TOMERGE.RATEONETTO,
						    TOMERGE.SPESECOMM,
						    TOMERGE.TASSAZIONE,
						    TOMERGE.VALUTA,
						    TOMERGE.STORNO,
						    TOMERGE.CTV_MERCATO,
						    TOMERGE.CTV_MERCATO_DIVISA,
						    TOMERGE.DATA_REGISTRAZIONE,
						    TOMERGE.DATA_SOTTOSCRIZIONE,
						    TOMERGE.PREZZO_MERCATO,
						    TOMERGE.N_OPERAZIONE_STORNO,
						    TOMERGE.F_CANCELLATO,
						    TOMERGE.C_CANALE,
						    TOMERGE.Z_CANALE,
						    TOMERGE.QTA_CAPITALE,
						    TOMERGE.PROVENIENZACAUSALE,
						    TOMERGE.D_AGGIORNAMENTO,
						    TOMERGE.C_PROCEDURA,
						    TOMERGE.BANCA_DA,
						    TOMERGE.CODICEAGENZIA_DA,
						    TOMERGE.CODICERAPPORTO_DA,
						    TOMERGE.BANCA_A,
						    TOMERGE.CODICEAGENZIA_A,
						    TOMERGE.CODICERAPPORTO_A,
						    TOMERGE.CODICERAPPORTO_ORI,
						    TOMERGE.CAUSALE_ORI,
						    TOMERGE.FONTE,
						    TOMERGE.IMPOSTA_REST);
					
		INSERT INTO output_print_table VALUES (to_number(to_char(sysdate,'YYYYMMDDHH24MISS')) || ' MERGE MOVIMENTI - COMMIT ON ROW: '|| I);
		COMMIT;
	
	END LOOP;
	
    PIPE ROW(i);
	RETURN;
END;