DECLARE

CURSOR DEL_CUR IS
	SELECT /*+ parallel(8) */ SCARTO.ROWID AS SCARTO_ROWID, 
			SCARTO.*, 
			TMP.ROWID AS TMP_ROWID
	FROM TBL_SCARTI_TMP_PFMOV_INC_FONDO SCARTO
	LEFT JOIN TMP_PFMOV_INC_FONDO TMP
		ON( TMP.ID_TITOLO = SCARTO.ID_TITOLO
			AND TMP.RAMO = SCARTO.RAMO
			AND TMP.CODICE_PRODOTTO = SCARTO.CODICE_PRODOTTO
			AND TMP.NUMERO_POLIZZA = SCARTO.NUMERO_POLIZZA
			AND TMP.TIPO_TITOLO = SCARTO.TIPO_TITOLO
			AND TMP.DATA_EFFETTO_TITOLO = SCARTO.DATA_EFFETTO_TITOLO
			AND TMP.CODICE_MOTIVO_STORNO = SCARTO.CODICE_MOTIVO_STORNO
			AND TMP.DATA_CARICO = SCARTO.DATA_CARICO
			AND TMP.CODICE_FONDO = SCARTO.CODICE_FONDO
			)
	WHERE SCARTO.RIPROPONIBILE = 'S';

I 				NUMBER(38,0):=0;
REUSE_COUNT		NUMBER(38,0):=0;	


BEGIN

	FOR CUR_ITEM IN DEL_CUR 

		LOOP
			
		I := I+1;
		
		IF(CUR_ITEM.TMP_ROWID IS NULL) THEN
		
		INSERT /*+ append nologging parallel(8) */
				INTO TMP_PFMOV_INC_FONDO (	ID_TITOLO,
											RAMO,
											CODICE_PRODOTTO,
											NUMERO_POLIZZA,
											TIPO_TITOLO,
											DATA_EFFETTO_TITOLO,
											CODICE_MOTIVO_STORNO,
											DATA_CARICO,
											CODICE_FONDO,
											ISIN,
											QUOTE,
											NAV,
											IMPORTO,
											DATA_NAV,
											COSTO_ETF
										)
								VALUES (CUR_ITEM.ID_TITOLO,
										CUR_ITEM.RAMO,
										CUR_ITEM.CODICE_PRODOTTO,
										CUR_ITEM.NUMERO_POLIZZA,
										CUR_ITEM.TIPO_TITOLO,
										CUR_ITEM.DATA_EFFETTO_TITOLO,
										CUR_ITEM.CODICE_MOTIVO_STORNO,
										CUR_ITEM.DATA_CARICO,
										CUR_ITEM.CODICE_FONDO,
										CUR_ITEM.ISIN,
										TO_NUMBER(CUR_ITEM.QUOTE, '999999999999999999999999999.999999999999999999999999999'),
										TO_NUMBER(CUR_ITEM.NAV, '999999999999999999999999999.999999999999999999999999999'),           
										TO_NUMBER(CUR_ITEM.IMPORTO, '999999999999999999999999999.999999999999999999999999999'),
										CUR_ITEM.DATA_NAV,
										TO_NUMBER(CUR_ITEM.COSTO_ETF, '999999999999999999999999999.999999999999999999999999999')         
								);
										
				REUSE_COUNT := REUSE_COUNT + 1;			
				
			END IF;		
			
			DELETE /*+ nologging */ FROM TBL_SCARTI_TMP_PFMOV_INC_FONDO TBL
			WHERE TBL.ROWID = CUR_ITEM.SCARTO_ROWID;
						
		IF MOD(I,10000) = 0 THEN
			INSERT INTO OUTPUT_PRINT_TABLE VALUES (TO_NUMBER(TO_CHAR(SYSDATE,'YYYYMMDDHH24MISS')) || ' REUSE SCARTI TMP_PFMOV_INC_FONDO. COMMIT ON ROW: ' || I);
			COMMIT;
		END IF;

		END LOOP;
			INSERT INTO OUTPUT_PRINT_TABLE VALUES (TO_NUMBER(TO_CHAR(SYSDATE,'YYYYMMDDHH24MISS')) || ' REUSE SCARTI TMP_PFMOV_INC_FONDO. RECORD RECUPERATI: ' || REUSE_COUNT);
		COMMIT;

END;