DECLARE

CURSOR DEL_CUR IS
	SELECT /*+ parallel(8) */ SCARTO.ROWID AS SCARTO_ROWID, 
			SCARTO.*, 
			TMP.ROWID AS TMP_ROWID
	FROM TBL_SCARTI_TMP_QUOTAZIONE_R3 SCARTO
	LEFT JOIN TMP_QUOTAZIONE_R3 TMP
		ON( TMP.CODICE_PRODOTTO = SCARTO.CODICE_PRODOTTO
			AND TMP.CODICE_FONDO = SCARTO.CODICE_FONDO
			AND TMP.DATA_RIFERIMENTO = SCARTO.DATA_RIFERIMENTO
			)
	WHERE SCARTO.RIPROPONIBILE = 'S';

I 				NUMBER(38,0):=0;
REUSE_COUNT		NUMBER(38,0):=0;	


BEGIN

	FOR CUR_ITEM IN DEL_CUR 

		LOOP
			
		I := I+1;
		
		IF(CUR_ITEM.TMP_ROWID IS NULL) THEN
		
		INSERT /*+ append nologging parallel(8) */
				INTO TMP_QUOTAZIONE_R3 (	CODICE_PRODOTTO,
											CODICE_FONDO,
											DESCRIZIONE_FONDO,
											DATA_RIFERIMENTO,
											VALORE
										)
								VALUES (CUR_ITEM.CODICE_PRODOTTO,
										CUR_ITEM.CODICE_FONDO,
										CUR_ITEM.DESCRIZIONE_FONDO,
										CUR_ITEM.DATA_RIFERIMENTO,
										TO_NUMBER(CUR_ITEM.VALORE, '999999999999999999999999999.999999999999999999999999999')        
								);
										
				REUSE_COUNT := REUSE_COUNT + 1;			
				
			END IF;		
			
			DELETE /*+ nologging */ FROM TBL_SCARTI_TMP_QUOTAZIONE_R3 TBL
			WHERE TBL.ROWID = CUR_ITEM.SCARTO_ROWID;
						
		IF MOD(I,10000) = 0 THEN
			INSERT INTO OUTPUT_PRINT_TABLE VALUES (TO_NUMBER(TO_CHAR(SYSDATE,'YYYYMMDDHH24MISS')) || ' REUSE SCARTI TMP_QUOTAZIONE_R3. COMMIT ON ROW: ' || I);
			COMMIT;
		END IF;

		END LOOP;
			INSERT INTO OUTPUT_PRINT_TABLE VALUES (TO_NUMBER(TO_CHAR(SYSDATE,'YYYYMMDDHH24MISS')) || ' REUSE SCARTI TMP_QUOTAZIONE_R3. RECORD RECUPERATI: ' || REUSE_COUNT);
		COMMIT;

END;