DECLARE

CURSOR SCARTI_PREZZI IS
SELECT /*+ parallel(8) */  TMP.ROWID, TMP.DATAPREZZO AS TMP_DATA, TMP.* 
FROM TMP_PFPREZZI_TITOLI TMP
INNER JOIN (SELECT B.CODICEBANCA, B.CODICETITOLO, B.DATAPREZZO AS DATA
	  		FROM (
					SELECT 	CODICEBANCA,                
							CODICETITOLO,               
							DATAPREZZO,                 
							CODICEDIVISA,             
							PREZZOCONTROVALORE,         
							PREZZOMERCATO,              
							RATEOLORDO,                 
							RATEONETTO,                 
							RATEODISAGGIO,              
							RITENUTADISAGGIO,           
							DATARATEO,                  
							CODICEFONTE,                
							COEFFICIENTECORREZIONE,     
							POOLFACTOR,                 
							COEFFICIENTEINDICIZZAZIONE, 
							DESCRCOEFFINDICIZZAZIONE,   
							MOLTIPLICATORE,             
							PREZZOCONTROVALORELORDISTA, 
							DATAAGGIORNAMENTO           
					FROM TMP_PFPREZZI_TITOLI
					GROUP BY CODICEBANCA,CODICETITOLO,DATAPREZZO,CODICEDIVISA,PREZZOCONTROVALORE,PREZZOMERCATO,RATEOLORDO,RATEONETTO,RATEODISAGGIO,              
							RITENUTADISAGGIO,DATARATEO,CODICEFONTE,COEFFICIENTECORREZIONE,POOLFACTOR,COEFFICIENTEINDICIZZAZIONE,DESCRCOEFFINDICIZZAZIONE,   
							MOLTIPLICATORE,PREZZOCONTROVALORELORDISTA,DATAAGGIORNAMENTO          
				) B
			GROUP BY B.CODICEBANCA, B.CODICETITOLO, B.DATAPREZZO
	  		HAVING COUNT(*) >1
	  		) A
ON TMP.CODICEBANCA = A.CODICEBANCA
AND TMP.CODICETITOLO = A.CODICETITOLO
AND TMP.DATAPREZZO = A.DATA;

I NUMBER(38,0):=0;

BEGIN

	 
	
	
	
FOR CUR_ITEM IN SCARTI_PREZZI
	LOOP 
				
	I := I+1;

	INSERT INTO TBL_SCARTI_TMP_PFPREZZI_TITOLI (	CODICEBANCA,               
											CODICETITOLO,             
											DATAPREZZO,                
											CODICEDIVISA,              
											PREZZOCONTROVALORE,        
											PREZZOMERCATO,             
											RATEOLORDO,                
											RATEONETTO,                
											RATEODISAGGIO,             
											RITENUTADISAGGIO,          
											DATARATEO,                 
											CODICEFONTE,               
											COEFFICIENTECORREZIONE,    
											POOLFACTOR,                
											COEFFICIENTEINDICIZZAZIONE,
											DESCRCOEFFINDICIZZAZIONE,  
											MOLTIPLICATORE,            
											PREZZOCONTROVALORELORDISTA,
											DATAAGGIORNAMENTO,         
											TMSTP,                     
											MOTIVO_SCARTO,             
											RIPROPONIBILE             )
									VALUES (CUR_ITEM.CODICEBANCA,               
											CUR_ITEM.CODICETITOLO,             
											CUR_ITEM.DATAPREZZO,                
											CUR_ITEM.CODICEDIVISA,              
											CUR_ITEM.PREZZOCONTROVALORE,        
											CUR_ITEM.PREZZOMERCATO,             
											CUR_ITEM.RATEOLORDO,                
											CUR_ITEM.RATEONETTO,                
											CUR_ITEM.RATEODISAGGIO,             
											CUR_ITEM.RITENUTADISAGGIO,          
											CUR_ITEM.DATARATEO,                 
											CUR_ITEM.CODICEFONTE,               
											CUR_ITEM.COEFFICIENTECORREZIONE,    
											CUR_ITEM.POOLFACTOR,                
											CUR_ITEM.COEFFICIENTEINDICIZZAZIONE,
											CUR_ITEM.DESCRCOEFFINDICIZZAZIONE,  
											CUR_ITEM.MOLTIPLICATORE,            
											CUR_ITEM.PREZZOCONTROVALORELORDISTA,
											CUR_ITEM.DATAAGGIORNAMENTO,         
											SYSDATE,
											'CHIAVE PRIMARIA "CODICEBANCA, CODICETITOLO, DATAPREZZO" DUPLICATA',
											'N'
											);
											
						DELETE /*+ nologging */  FROM TMP_PFPREZZI_TITOLI TMP_DEL
						WHERE TMP_DEL.ROWID = CUR_ITEM.ROWID;
			
		IF MOD(I,10000) = 0 THEN
		INSERT INTO OUTPUT_PRINT_TABLE VALUES (TO_NUMBER(TO_CHAR(SYSDATE,'YYYYMMDDHH24MISS')) || ' SCARTI TMP_PFPREZZI_TITOLI PER CHIAVE (CODICEBANCA, CODICETITOLO, DATAPREZZO) DUPLICATA - COMMIT ON ROW: '|| I);
		COMMIT; 
		END IF;
				
	END LOOP;
		INSERT INTO OUTPUT_PRINT_TABLE VALUES (TO_NUMBER(TO_CHAR(SYSDATE,'YYYYMMDDHH24MISS')) || ' SCARTI TMP_PFPREZZI_TITOLI PER CHIAVE (CODICEBANCA, CODICETITOLO, DATAPREZZO) DUPLICATA. RECORD ELABORATI: '|| I);
	COMMIT;
END;