DECLARE

CURSOR SCARTI_PREZZI IS
    SELECT /*+ parallel(8) */ SF.CODICETITOLO AS SF_CODICETITOLO,
        TMP.ROWID,
        TMP.*
    FROM TMP_PFPREZZI TMP
    	LEFT JOIN STRUMENTOFINANZIARIO SF
    		ON SF.CODICETITOLO = TMP.CODICETITOLO
    WHERE SF.CODICETITOLO IS NULL;

I 						NUMBER(38,0) :=0;
SCARTI_CODICETITOLO 	NUMBER :=0;


BEGIN

FOR CUR_ITEM IN SCARTI_PREZZI
    LOOP
        I := I+1;

	INSERT INTO TBL_SCARTI_TMP_PFPREZZI (	CODICEBANCA,               
											CODICETITOLO,             
											DATAPREZZO,                
											CODICEDIVISA,              
											PREZZOCONTROVALORE,        
											PREZZOMERCATO,             
											RATEOLORDO,                
											RATEONETTO,                
											RATEODISAGGIO,             
											RITENUTADISAGGIO,          
											DATARATEO,                 
											CODICEFONTE,               
											COEFFICIENTECORREZIONE,    
											POOLFACTOR,                
											COEFFICIENTEINDICIZZAZIONE,
											DESCRCOEFFINDICIZZAZIONE,  
											MOLTIPLICATORE,            
											PREZZOCONTROVALORELORDISTA,
											DATAAGGIORNAMENTO,         
											TMSTP,
											RIPROPONIBILE,
											MOTIVO_SCARTO             											             
											)
									VALUES (CUR_ITEM.CODICEBANCA,               
											CUR_ITEM.CODICETITOLO,             
											CUR_ITEM.DATAPREZZO,                
											CUR_ITEM.CODICEDIVISA,              
											CUR_ITEM.PREZZOCONTROVALORE,        
											CUR_ITEM.PREZZOMERCATO,             
											CUR_ITEM.RATEOLORDO,                
											CUR_ITEM.RATEONETTO,                
											CUR_ITEM.RATEODISAGGIO,             
											CUR_ITEM.RITENUTADISAGGIO,          
											CUR_ITEM.DATARATEO,                 
											CUR_ITEM.CODICEFONTE,               
											CUR_ITEM.COEFFICIENTECORREZIONE,    
											CUR_ITEM.POOLFACTOR,                
											CUR_ITEM.COEFFICIENTEINDICIZZAZIONE,
											CUR_ITEM.DESCRCOEFFINDICIZZAZIONE,  
											CUR_ITEM.MOLTIPLICATORE,            
											CUR_ITEM.PREZZOCONTROVALORELORDISTA,
											CUR_ITEM.DATAAGGIORNAMENTO,         
								            SYSDATE,
								            'S',
								            'CHIAVE ESTERNA "CODICETITOLO" NON CENSITA'
								       	 	);

	DELETE  /*+ nologging */ FROM TMP_PFPREZZI TMP_DEL 
	WHERE TMP_DEL.ROWID = CUR_ITEM.ROWID;
	
	SCARTI_CODICETITOLO := SCARTI_CODICETITOLO +1;
	
	IF MOD(I,10000) = 0 THEN
	    INSERT
	    INTO
	        OUTPUT_PRINT_TABLE VALUES( TO_NUMBER(TO_CHAR(SYSDATE,'YYYYMMDDHH24MISS')) ||' SCARTI TMP_PFPREZZI PER CHIAVE ESTERNA (CODICETITOLO) NON CENSITA - COMMIT ON ROW: ' || I);
		COMMIT;
	END IF;

END LOOP;

INSERT INTO OUTPUT_PRINT_TABLE VALUES( TO_NUMBER(TO_CHAR(SYSDATE,'YYYYMMDDHH24MISS')) ||' SCARTI TMP_PFPREZZI PER CHIAVE ESTERNA (CODICETITOLO) NON CENSITA. RECORD ELABORATI: '|| I);
INSERT INTO OUTPUT_PRINT_TABLE VALUES(TO_NUMBER(TO_CHAR(SYSDATE,'YYYYMMDDHH24MISS')) || ' SCARTI TMP_PFPREZZI PER CHIAVE ESTERNA (CODICETITOLO) NON CENSITA. RECORD SCARTATI: ' || SCARTI_CODICETITOLO);

COMMIT;
END;