DECLARE

CURSOR SCARTI_MOVIMENTI IS
SELECT   TMP.ROWID, TMP.* 
FROM TMP_PFMOV_FONDI TMP
INNER JOIN (SELECT TMP2.CODICE, 
				   CASE 
				   	WHEN TMP2.TIPORAPPORTO = '02' 
				   		THEN NVL(TMP2.CODICEINTERNO,'LIQ_EUR_LIB')
				   	ELSE TMP2.CODICEINTERNO
				   	END AS CODICEINTERNO, 
				   	TMP2.CODICERAPPORTO
			 FROM TMP_PFMOV_FONDI TMP2
			 GROUP BY TMP2.CODICE, 
			 		  CASE 
					   	WHEN TMP2.TIPORAPPORTO = '02' 
					   		THEN NVL(TMP2.CODICEINTERNO,'LIQ_EUR_LIB')
					   	ELSE TMP2.CODICEINTERNO
					   	END, 
					TMP2.CODICERAPPORTO
			 HAVING COUNT(*) >1) A
ON TMP.CODICE = A.CODICE
AND CASE 
		WHEN TMP.TIPORAPPORTO = '02' 
			THEN NVL(TMP.CODICEINTERNO,'LIQ_EUR_LIB')
		ELSE TMP.CODICEINTERNO END =A.CODICEINTERNO
AND TMP.CODICERAPPORTO = A.CODICERAPPORTO;


	TYPE SCARTI_MOVIMENTI_TYPE IS TABLE OF SCARTI_MOVIMENTI%ROWTYPE INDEX BY PLS_INTEGER;
	
	RES_SCARTI_MOVIMENTI SCARTI_MOVIMENTI_TYPE;
	
	ROWS      PLS_INTEGER := 10000;
	        
	I 			NUMBER(38,0);
	TOTALE			NUMBER(38,0):=0;
	
	BEGIN
	
	 
	
	
	
	OPEN SCARTI_MOVIMENTI;
	LOOP
			FETCH SCARTI_MOVIMENTI BULK COLLECT INTO RES_SCARTI_MOVIMENTI LIMIT ROWS;
				EXIT WHEN RES_SCARTI_MOVIMENTI.COUNT = 0;  
				
	      I:=0;
	      I:= RES_SCARTI_MOVIMENTI.COUNT;
	      TOTALE := TOTALE + I;
				
				FORALL J IN RES_SCARTI_MOVIMENTI.FIRST .. RES_SCARTI_MOVIMENTI.LAST		
	
				INSERT   INTO TBL_SCARTI_TMP_PFMOV_FONDI (	CODICEBANCA,       
															CODICE,            
															CODICEAGENZIA,    
															CODICERAPPORTO,    
															TIPORAPPORTO,      
															CODICEINTERNO,     
															CAUSALE,           
															CTVREGOLATO,       
															CTVMERCATO,        
															CTVREGOLATODIVISA, 
															CTVMERCATODIVISA,  
															DIVISA,            
															QUANTITA,          
															PREZZOMERCATO,    
															PREZZO,            
															RATEOLORDO,       
															RATEONETTO,        
															CAMBIO,            
															DATAORDINE,        
															DATACONTABILE,     
															DATAVALUTA,     
															FLAGSTORNO,        
															CODICESTORNO,      
															FLAGCANCELLATO,    
															IMPOSTE,           
															COMMISSIONI,       
															DATAAGGIORNAMENTO, 
															TMSTP,             
															MOTIVO_SCARTO,     
															RIPROPONIBILE
														)
												VALUES (RES_SCARTI_MOVIMENTI(J).CODICEBANCA,       
														RES_SCARTI_MOVIMENTI(J).CODICE,            
														RES_SCARTI_MOVIMENTI(J).CODICEAGENZIA,    
														RES_SCARTI_MOVIMENTI(J).CODICERAPPORTO,    
														RES_SCARTI_MOVIMENTI(J).TIPORAPPORTO,      
														RES_SCARTI_MOVIMENTI(J).CODICEINTERNO,     
														RES_SCARTI_MOVIMENTI(J).CAUSALE,           
														RES_SCARTI_MOVIMENTI(J).CTVREGOLATO,       
														RES_SCARTI_MOVIMENTI(J).CTVMERCATO,        
														RES_SCARTI_MOVIMENTI(J).CTVREGOLATODIVISA, 
														RES_SCARTI_MOVIMENTI(J).CTVMERCATODIVISA,  
														RES_SCARTI_MOVIMENTI(J).DIVISA,            
														RES_SCARTI_MOVIMENTI(J).QUANTITA,          
														RES_SCARTI_MOVIMENTI(J).PREZZOMERCATO,    
														RES_SCARTI_MOVIMENTI(J).PREZZO,            
														RES_SCARTI_MOVIMENTI(J).RATEOLORDO,       
														RES_SCARTI_MOVIMENTI(J).RATEONETTO,        
														RES_SCARTI_MOVIMENTI(J).CAMBIO,            
														RES_SCARTI_MOVIMENTI(J).DATAORDINE,        
														RES_SCARTI_MOVIMENTI(J).DATACONTABILE,     
														RES_SCARTI_MOVIMENTI(J).DATAVALUTA,     
														RES_SCARTI_MOVIMENTI(J).FLAGSTORNO,        
														RES_SCARTI_MOVIMENTI(J).CODICESTORNO,      
														RES_SCARTI_MOVIMENTI(J).FLAGCANCELLATO,    
														RES_SCARTI_MOVIMENTI(J).IMPOSTE,           
														RES_SCARTI_MOVIMENTI(J).COMMISSIONI,       
														RES_SCARTI_MOVIMENTI(J).DATAAGGIORNAMENTO,
														SYSDATE,
														'CHIAVE PRIMARIA "CODICE, CODICEINTERNO, CODICERAPPORTO" DUPLICATA',
														'N'
														);
				
			        COMMIT;		
			        
			        FORALL J IN RES_SCARTI_MOVIMENTI.FIRST .. RES_SCARTI_MOVIMENTI.LAST
			        	
			        DELETE   FROM TMP_PFMOV_FONDI TMP_DEL
					WHERE TMP_DEL.ROWID = RES_SCARTI_MOVIMENTI(J).ROWID;
					
					COMMIT;
			        	
	            
	             INSERT INTO OUTPUT_PRINT_TABLE VALUES (TO_NUMBER(TO_CHAR(SYSDATE,'YYYYMMDDHH24MISS')) || ' SCARTI TMP_PFMOV_FONDI PER CHIAVE (CODICE, CODICEINTERNO, CODICERAPPORTO) DUPLICATA: ' || I || ' RECORD');
			        
	END LOOP;
	CLOSE SCARTI_MOVIMENTI;
	
	INSERT INTO OUTPUT_PRINT_TABLE VALUES (TO_NUMBER(TO_CHAR(SYSDATE,'YYYYMMDDHH24MISS')) || ' SCARTI TMP_PFMOV_FONDI PER CHIAVE (CODICE, CODICEINTERNO, CODICERAPPORTO) DUPLICATA: ' || TOTALE);
	COMMIT;
END;