DECLARE

--Eliminare dalla tmp i record con flagesclusione = '1' e censire il codicetitolo sulla tabella PRODOTTI_DA_ESCLUDERE

I 	NUMBER(38,0) :=0;
	

BEGIN
		

	MERGE INTO PRODOTTI_DA_ESCLUDERE PDE
		USING(
				SELECT DISTINCT
						CODICEINTERNO         AS CODICETITOLO,
						SYSDATE 			  AS DATAINSERIMENTO,
						'PZ'				  AS TIPO,
						'SALDI'				  AS DESCRIZIONE
				FROM  TMP_PFSALPOL_RECUP 
				WHERE flagesclusione = '1'
				) T
	ON (PDE.CODICETITOLO = T.CODICETITOLO)
			
	WHEN MATCHED THEN UPDATE
		SET
			PDE.DATAINSERIMENTO = T.DATAINSERIMENTO,
			PDE.TIPO = T.TIPO,
			PDE.DESCRIZIONE = T.DESCRIZIONE
	
	WHEN NOT MATCHED 
	THEN INSERT
			(	CODICETITOLO,
				DATAINSERIMENTO,
				TIPO,
				DESCRIZIONE
			)
			VALUES
			(   T.CODICETITOLO,
				T.DATAINSERIMENTO,
				T.TIPO,
				T.DESCRIZIONE
			);
	
			COMMIT;
	 
	DELETE /*+ nologging */  FROM TMP_PFSALPOL_RECUP TMP_DEL
	WHERE TMP_DEL.CODICEINTERNO IN (SELECT DISTINCT codicetitolo
									 FROM PRODOTTI_DA_ESCLUDERE);

INSERT INTO OUTPUT_PRINT_TABLE VALUES (TO_NUMBER(TO_CHAR(SYSDATE,'YYYYMMDDHH24MISS')) || ' SCARTI TMP_PFSALPOL_RECUP SCARTI FLAGESCLUSIONE = 1. RECORD ELIMINATI');
		
COMMIT;
		
END;