DECLARE

--Eliminare dalla tmp i record con tiporapporto 01 e 03
CURSOR DEL_SALDI_MOVIMP IS
	SELECT /*+ parallel(8) */ SM.ROWID, SM.* 
	FROM TMP_PFSALDI_MOVIMP SM
	WHERE SM.TIPORAPPORTO in ('01', '03');

I 	NUMBER(38,0) :=0;


BEGIN
		
FOR CUR_ITEM IN DEL_SALDI_MOVIMP

	LOOP 			
	
	 I := I+1;
	 
	DELETE /*+ nologging */ FROM TMP_PFSALDI_MOVIMP TMP_DEL
	WHERE TMP_DEL.ROWID = CUR_ITEM.ROWID;
					
	IF MOD(I,10000) = 0 THEN
		INSERT INTO OUTPUT_PRINT_TABLE VALUES (TO_NUMBER(TO_CHAR(SYSDATE,'YYYYMMDDHH24MISS')) || ' SCARTI TMP_PFSALDI_MOVIMP TIPORAPPORTO 01 03 - COMMIT ON ROW: '|| I);
		COMMIT; 
	END IF;
					
	END LOOP;

INSERT INTO OUTPUT_PRINT_TABLE VALUES (TO_NUMBER(TO_CHAR(SYSDATE,'YYYYMMDDHH24MISS')) || ' SCARTI TMP_PFSALDI_MOVIMP TIPORAPPORTO 01 03. RECORD ELIMINATI: '|| I);
		
COMMIT;
		
END;