DECLARE

--Eliminare dalla tmp i record con data antecedente al 20171231
CURSOR DEL_MOV_ANTE IS
	SELECT /*+ parallel(8) */ SM.ROWID, SM.* 
	FROM TMP_PFMOV_TITOLI SM
	WHERE TO_NUMBER(TO_CHAR(TO_DATE(DATAVALUTA, 'YYYY-MM-DD'), 'YYYYMMDD')) < 20171231
	AND TIPORAPPORTO != '14'

	UNION
	
	SELECT /*+ parallel(8) */ SM.ROWID, SM.* 
	FROM TMP_PFMOV_TITOLI SM
	WHERE TO_NUMBER(TO_CHAR(TO_DATE(DATACONTABILE, 'YYYY-MM-DD'), 'YYYYMMDD')) < 20171231
	AND TIPORAPPORTO = '14';

I 	NUMBER(38,0) :=0;


BEGIN
		
FOR CUR_ITEM IN DEL_MOV_ANTE

	LOOP 			
	
	 I := I+1;
	 
	DELETE /*+ nologging */ FROM TMP_PFMOV_TITOLI TMP_DEL
	WHERE TMP_DEL.ROWID = CUR_ITEM.ROWID;
					
	IF MOD(I,10000) = 0 THEN
		INSERT INTO OUTPUT_PRINT_TABLE VALUES (TO_NUMBER(TO_CHAR(SYSDATE,'YYYYMMDDHH24MISS')) || ' SCARTI TMP_PFMOV_TITOLI DATA ANTECEDENTE AL 20171231 - COMMIT ON ROW: '|| I);
		COMMIT; 
	END IF;
					
	END LOOP;

INSERT INTO OUTPUT_PRINT_TABLE VALUES (TO_NUMBER(TO_CHAR(SYSDATE,'YYYYMMDDHH24MISS')) || ' SCARTI TMP_PFMOV_TITOLI DATA ANTECEDENTE AL 20171231. RECORD ELIMINATI: '|| I);
		
COMMIT;
		
END;