-- SCARTO PER CHIAVE ESTERNA CODICEDIVISAINCERTO NON CENSITA: 

DECLARE 

CURSOR CAMBI_NON_CENSITI IS
	SELECT /*+ parallel(8) */  SF.DIVISA AS DIVISA_SF, TMP.ROWID, TMP.* 
	FROM TMP_PFCAMBI TMP
	LEFT JOIN STRUMENTOFINANZIARIO SF
		ON SF.DIVISA= TMP.CODICEDIVISACERTO
		AND SF.TIPO= 'CUR'
	WHERE SF.DIVISA IS NULL;

I 				NUMBER(38,0):=0;
COUNT_SCARTI 	NUMBER:=0;


BEGIN
	
FOR CUR_ITEM IN CAMBI_NON_CENSITI
	LOOP 
	
	I := I+1;
	
		INSERT INTO TBL_SCARTI_TMP_PFCAMBI (CODICEBANCA,
									        CODICEDIVISACERTO,
									        CODICEDIVISAINCERTO,
									        DATACAMBIO,
									        CAMBIO,
									        DATAAGGIORNAMENTO,
									        TMSTP,
									        MOTIVO_SCARTO,
									        RIPROPONIBILE
										)
										VALUES 
										(
											CUR_ITEM.CODICEBANCA,
											CUR_ITEM.CODICEDIVISACERTO, 
											CUR_ITEM.CODICEDIVISAINCERTO, 
											CUR_ITEM.DATACAMBIO, 
											CUR_ITEM.CAMBIO, 
											CUR_ITEM.DATAAGGIORNAMENTO, 
											SYSDATE,
											'CHIAVE ESTERNA "CODICEDIVISAINCERTO" NON CENSITA',
											'S'
										);

			DELETE   FROM TMP_PFCAMBI DEL_TMP
			WHERE DEL_TMP.ROWID = CUR_ITEM.ROWID;
			
			COUNT_SCARTI := COUNT_SCARTI+1;
	
		IF MOD(I,10000) = 0 THEN
		INSERT INTO OUTPUT_PRINT_TABLE VALUES (TO_NUMBER(TO_CHAR(SYSDATE,'YYYYMMDDHH24MISS')) || 'SCARTI TMP_PFCAMBI PER CHIAVE ESTERNA (CODICEDIVISAINCERTO) NON CENSITA - COMMIT ON ROW: '|| I);
		COMMIT; 
		END IF;
				
	END LOOP;
	INSERT INTO OUTPUT_PRINT_TABLE VALUES (TO_NUMBER(TO_CHAR(SYSDATE,'YYYYMMDDHH24MISS')) || ' SCARTI TMP_PFCAMBI PER CHIAVE ESTERNA (CODICEDIVISAINCERTO) NON CENSITA. NUMERO RECORD SCARTATI: ' || COUNT_SCARTI);
	COMMIT;
END;