-- SCARTI TMP_CAMBI PER CHIAVE DUPLICATA (CODICEBANCA, CODICEDIVISACERTO, CODICEDIVISAINCERTO, DATACAMBIO)
DECLARE

CURSOR SCARTI_CAMBI IS
 
SELECT /*+ parallel(8) */  TMP.ROWID, TMP.*
FROM TMP_PFCAMBI TMP
INNER JOIN (SELECT
                    CODICEBANCA,
                    CODICEDIVISACERTO,
                    CODICEDIVISAINCERTO,
                    DATACAMBIO
                FROM
                    TMP_PFCAMBI
                GROUP BY
                    CODICEBANCA,
                    CODICEDIVISACERTO,
                    CODICEDIVISAINCERTO,
                    DATACAMBIO
                HAVING
                    COUNT(*) >1)  A
ON TMP.CODICEBANCA=A.CODICEBANCA
AND TMP.CODICEDIVISACERTO=A.CODICEDIVISACERTO
AND TMP.CODICEDIVISAINCERTO =A.CODICEDIVISAINCERTO
AND TMP.DATACAMBIO=A.DATACAMBIO;
    
    
I NUMBER(38,0):=0;

BEGIN
	
	 
	
	
	
    FOR CUR_ITEM IN SCARTI_CAMBI
    LOOP
        I := I+1;
		INSERT  
		INTO
		    TBL_SCARTI_TMP_PFCAMBI
		    (
		        CODICEBANCA,
		        CODICEDIVISACERTO,
		        CODICEDIVISAINCERTO,
		        DATACAMBIO,
		        CAMBIO,
		        DATAAGGIORNAMENTO,
		        TMSTP,
		        MOTIVO_SCARTO,
		        RIPROPONIBILE
		    )
		    VALUES
		    (
		        CUR_ITEM.CODICEBANCA,
		        CUR_ITEM.CODICEDIVISACERTO,
		        CUR_ITEM.CODICEDIVISAINCERTO,
		        CUR_ITEM.DATACAMBIO,
		        CUR_ITEM.CAMBIO,
		        CUR_ITEM.DATAAGGIORNAMENTO,
		        SYSDATE,
		        'CHIAVE PRIMARIA "CODICEBANCA, CODICEDIVISACERTO, CODICEDIVISAINCERTO, DATACAMBIO" DUPLICATA',
		        'N'
		    );

    DELETE   FROM TMP_PFCAMBI DEL_TMP
	WHERE DEL_TMP.ROWID = CUR_ITEM.ROWID;
   

		IF MOD(I,10000) = 0 THEN
		    INSERT INTO OUTPUT_PRINT_TABLE VALUES (TO_NUMBER(TO_CHAR(SYSDATE,'YYYYMMDDHH24MISS')) || ' SCARTI TMP_PFCAMBI PER CHIAVE (CODICEBANCA, CODICEDIVISACERTO, CODICEDIVISAINCERTO, DATACAMBIO) DUPLICATA - COMMIT ON ROW: '|| I);
		COMMIT;
		END IF;
	END LOOP;
	INSERT INTO OUTPUT_PRINT_TABLE VALUES (TO_NUMBER(TO_CHAR(SYSDATE,'YYYYMMDDHH24MISS')) || ' SCARTI TMP_PFCAMBI PER CHIAVE (CODICEBANCA, CODICEDIVISACERTO, CODICEDIVISAINCERTO, DATACAMBIO) DUPLICATA. NUMERO RECORD ELABORATI: ' || I);
	COMMIT;
END;