DECLARE
CURSOR SCARTI_COSTI_MOVIMENTO IS
SELECT /*+ parallel(8) */  TMP.ROWID, TMP.* 
FROM TMP_PFCOSTI_TITOLI TMP
INNER JOIN (SELECT CODICEBANCA,CODICECOSTO,CODICEMOVIMENTO,TIPORAPPORTO
	    FROM TMP_PFCOSTI_TITOLI TCOST
	    GROUP BY CODICEBANCA,CODICECOSTO,CODICEMOVIMENTO,TIPORAPPORTO
	    HAVING COUNT(*) >1) A
ON TMP.CODICEBANCA = A.CODICEBANCA
AND TMP.CODICECOSTO=A.CODICECOSTO
AND TMP.CODICEMOVIMENTO = A.CODICEMOVIMENTO
AND TMP.TIPORAPPORTO = A.TIPORAPPORTO;


	TYPE SCARTI_COSTI_MOVIMENTO_TYPE IS TABLE OF SCARTI_COSTI_MOVIMENTO%ROWTYPE INDEX BY PLS_INTEGER;
	
	RES_SCARTI_COSTI_MOVIMENTO SCARTI_COSTI_MOVIMENTO_TYPE;
	
	ROWS      PLS_INTEGER := 10000;
	        
	I 				NUMBER(38,0);
	TOTALE			NUMBER(38,0):=0;
	
	BEGIN
	
	 
	
	
	
	OPEN SCARTI_COSTI_MOVIMENTO;
	LOOP
			FETCH SCARTI_COSTI_MOVIMENTO BULK COLLECT INTO RES_SCARTI_COSTI_MOVIMENTO LIMIT ROWS;
				EXIT WHEN RES_SCARTI_COSTI_MOVIMENTO.COUNT = 0;  
				
	      I:=0;
	      I:= RES_SCARTI_COSTI_MOVIMENTO.COUNT;
	      TOTALE := TOTALE + I;
				
				FORALL J IN RES_SCARTI_COSTI_MOVIMENTO.FIRST .. RES_SCARTI_COSTI_MOVIMENTO.LAST		
	
				INSERT    INTO TBL_SCARTI_TMP_PFCOSTI_TITOLI (CODICEBANCA,       
													CODICEMOVIMENTO,  
													CODICECOSTO,  
													IMPORTO,      
													FONTE,          
													TIPORAPPORTO,      
													DATAAGGIORNAMENTO, 
													TMSTP,             
													MOTIVO_SCARTO,     
													RIPROPONIBILE     
													)
											VALUES (RES_SCARTI_COSTI_MOVIMENTO(J).CODICEBANCA,      
													RES_SCARTI_COSTI_MOVIMENTO(J).CODICEMOVIMENTO,  
													RES_SCARTI_COSTI_MOVIMENTO(J).CODICECOSTO,      
													RES_SCARTI_COSTI_MOVIMENTO(J).IMPORTO,          
													RES_SCARTI_COSTI_MOVIMENTO(J).FONTE,            
													RES_SCARTI_COSTI_MOVIMENTO(J).TIPORAPPORTO,     
													RES_SCARTI_COSTI_MOVIMENTO(J).DATAAGGIORNAMENTO,
													SYSDATE,
													'CHIAVE PRIMARIA "CODICEBANCA,CODICECOSTO,CODICEMOVIMENTO,TIPORAPPORTO" DUPLICATA',
													'N'
													);
				
			        COMMIT;		
			        
			        FORALL J IN RES_SCARTI_COSTI_MOVIMENTO.FIRST .. RES_SCARTI_COSTI_MOVIMENTO.LAST
			        	
			        DELETE   FROM TMP_PFCOSTI_TITOLI TMP_DEL
					WHERE TMP_DEL.ROWID = RES_SCARTI_COSTI_MOVIMENTO(J).ROWID;
					
					COMMIT;
			        	
	            
	             INSERT INTO OUTPUT_PRINT_TABLE VALUES (TO_NUMBER(TO_CHAR(SYSDATE,'YYYYMMDDHH24MISS')) || ' SCARTI TMP_PFCOSTI_TITOLI PER CHIAVE (CODICEBANCA,CODICECOSTO,CODICEMOVIMENTO,TIPORAPPORTO) DUPLICATA: ' || I || ' RECORD');
			        
	END LOOP;
	CLOSE SCARTI_COSTI_MOVIMENTO;
	
	INSERT INTO OUTPUT_PRINT_TABLE VALUES (TO_NUMBER(TO_CHAR(SYSDATE,'YYYYMMDDHH24MISS')) || ' SCARTI TMP_PFCOSTI_TITOLI PER CHIAVE (CODICEBANCA,CODICECOSTO,CODICEMOVIMENTO,TIPORAPPORTO) DUPLICATA: ' || TOTALE);
	COMMIT;
END;