DECLARE
CURSOR SCARTI_SALDI_REND IS
SELECT /*+ parallel(8) */  TMP.ROWID, TMP.* 
FROM TMP_PFSALDISTORICI TMP
INNER JOIN (
SELECT CODICERAPPORTO, CODICEINTERNO, DATASALDO
	  FROM TMP_PFSALDISTORICI
	  GROUP BY CODICERAPPORTO, CODICEINTERNO, DATASALDO
	  HAVING COUNT(*) >1) A
ON TMP.CODICERAPPORTO = A.CODICERAPPORTO
AND TMP.CODICEINTERNO = A.CODICEINTERNO
AND TMP.DATASALDO = A.DATASALDO;
	            
	TYPE SCARTI_SALDI_REND_TYPE IS TABLE OF SCARTI_SALDI_REND%ROWTYPE INDEX BY PLS_INTEGER;
	
	RES_SCARTI_SALDI_REND SCARTI_SALDI_REND_TYPE;
	
CURSOR SCARTI_SALDI_REND_BFPD IS
SELECT  /*+ parallel(8) */ TMP.ROWID, TMP.* 
FROM TMP_PFSALDISTORICI TMP
INNER JOIN (
SELECT id_buono_originario, CODICEINTERNO, DATASALDO
	  FROM TMP_PFSALDISTORICI
	  where id_buono_originario is not null
	  GROUP BY id_buono_originario, CODICEINTERNO, DATASALDO
	  HAVING COUNT(*) >1) A
ON TMP.id_buono_originario = A.id_buono_originario
AND TMP.CODICEINTERNO = A.CODICEINTERNO
AND TMP.DATASALDO = A.DATASALDO;
	            
	TYPE SCARTI_SALDI_REND_BFPD_TYPE IS TABLE OF SCARTI_SALDI_REND_BFPD%ROWTYPE INDEX BY PLS_INTEGER;
	
	RES_SCARTI_SALDI_REND_BFPD SCARTI_SALDI_REND_BFPD_TYPE;

	ROWS      PLS_INTEGER := 10000;
	        
	I 			NUMBER(38,0);
	TOTALE			NUMBER(38,0):=0;
	
	BEGIN
	
	 
	
	
		
	OPEN SCARTI_SALDI_REND;
	LOOP
			FETCH SCARTI_SALDI_REND BULK COLLECT INTO RES_SCARTI_SALDI_REND LIMIT ROWS;
				EXIT WHEN RES_SCARTI_SALDI_REND.COUNT = 0;  
				
	      I:=0;
	      I:= RES_SCARTI_SALDI_REND.COUNT;
	      TOTALE := TOTALE + I;
				
				FORALL J IN RES_SCARTI_SALDI_REND.FIRST .. RES_SCARTI_SALDI_REND.LAST		
	
				INSERT INTO TBL_SCARTI_TMP_PFSALDISTORICI( 	CODICEBANCA,       
															CODICEAGENZIA,     
															CODICERAPPORTO,    
															CODICEINTERNO,    
															DATASALDO,         
															TIPORAPPORTO,      
															CONTROVALORE,      
															DIVISA,            
															FLAGCONSOLIDATO,   
															CTVVERSATO,        
															CTVPRELEVATO,      
															CTVVERSATONETTO,    
															DATAAGGIORNAMENTO,
															CODICEFASCIARENDIMENTO,
															DECRIZIONEFASCIARENDIMENTO,
															SERIEBUONO,
															VALORESCADENZALORDO,
															FLAGNETTISTALORDISTA,
															IMPORTONETTO,
															VALORESCADENZANETTO,
															VALORENOMINALE,
															DATASOTTOSCRIZIONE,
															DATASCADENZA,
															TMSTP,             
															MOTIVO_SCARTO,     
															RIPROPONIBILE     
														)
												VALUES (RES_SCARTI_SALDI_REND(J).CODICEBANCA,       
														RES_SCARTI_SALDI_REND(J).CODICEAGENZIA,     
														RES_SCARTI_SALDI_REND(J).CODICERAPPORTO,    
														RES_SCARTI_SALDI_REND(J).CODICEINTERNO,     
														RES_SCARTI_SALDI_REND(J).DATASALDO,         
														RES_SCARTI_SALDI_REND(J).TIPORAPPORTO,      
														RES_SCARTI_SALDI_REND(J).CONTROVALORE,      
														RES_SCARTI_SALDI_REND(J).DIVISA,            
														RES_SCARTI_SALDI_REND(J).FLAGCONSOLIDATO,   
														RES_SCARTI_SALDI_REND(J).CTVVERSATO,        
														RES_SCARTI_SALDI_REND(J).CTVPRELEVATO,      
														RES_SCARTI_SALDI_REND(J).CTVVERSATONETTO,    
														RES_SCARTI_SALDI_REND(J).DATAAGGIORNAMENTO,
														RES_SCARTI_SALDI_REND(J).CODICEFASCIARENDIMENTO,
														RES_SCARTI_SALDI_REND(J).DECRIZIONEFASCIARENDIMENTO,
														RES_SCARTI_SALDI_REND(J).SERIEBUONO,
														RES_SCARTI_SALDI_REND(J).VALORESCADENZALORDO,
														RES_SCARTI_SALDI_REND(J).FLAGNETTISTALORDISTA,
														RES_SCARTI_SALDI_REND(J).IMPORTONETTO,
														RES_SCARTI_SALDI_REND(J).VALORESCADENZANETTO,
														RES_SCARTI_SALDI_REND(J).VALORENOMINALE,
														RES_SCARTI_SALDI_REND(J).DATASOTTOSCRIZIONE,
														RES_SCARTI_SALDI_REND(J).DATASCADENZA,
														SYSDATE,             
														'CHIAVE PRIMARIA "CODICERAPPORTO, CODICEINTERNO, DATASALDO" DUPLICATA',     
														'N'
														);
														
			COMMIT;
			
			FORALL J IN RES_SCARTI_SALDI_REND.FIRST .. RES_SCARTI_SALDI_REND.LAST
			
			DELETE  /*+ nologging */ FROM TMP_PFSALDISTORICI TMP_DEL
			WHERE TMP_DEL.ROWID = RES_SCARTI_SALDI_REND(J).ROWID;
				
				        
			        COMMIT;		        
	            
	             INSERT INTO OUTPUT_PRINT_TABLE VALUES (TO_NUMBER(TO_CHAR(SYSDATE,'YYYYMMDDHH24MISS')) || ' SCARTI TMP_PFSALDISTORICI PER CHIAVE CODICERAPPORTO, CODICEINTERNO, DATASALDO) DUPLICATA: ' || I || ' RECORD');
			        
	END LOOP;
	CLOSE SCARTI_SALDI_REND;
	
	INSERT INTO OUTPUT_PRINT_TABLE VALUES (TO_NUMBER(TO_CHAR(SYSDATE,'YYYYMMDDHH24MISS')) || ' SCARTI TMP_PFSALDISTORICI PER CHIAVE CODICERAPPORTO, CODICEINTERNO, DATASALDO) DUPLICATA: ' || TOTALE);
	COMMIT;

	TOTALE:=0;
	
	OPEN SCARTI_SALDI_REND_BFPD;
	LOOP
			FETCH SCARTI_SALDI_REND_BFPD BULK COLLECT INTO RES_SCARTI_SALDI_REND_BFPD LIMIT ROWS;
				EXIT WHEN RES_SCARTI_SALDI_REND_BFPD.COUNT = 0;  
				
	      I:=0;
	      I:= RES_SCARTI_SALDI_REND_BFPD.COUNT;
	      TOTALE := TOTALE + I;
				
				FORALL J IN RES_SCARTI_SALDI_REND_BFPD.FIRST .. RES_SCARTI_SALDI_REND_BFPD.LAST		
	
				INSERT INTO TBL_SCARTI_TMP_PFSALDISTORICI( 	CODICEBANCA,       
															CODICEAGENZIA,     
															CODICERAPPORTO,    
															CODICEINTERNO,    
															DATASALDO,         
															TIPORAPPORTO,      
															CONTROVALORE,      
															DIVISA,            
															FLAGCONSOLIDATO,   
															CTVVERSATO,        
															CTVPRELEVATO,      
															CTVVERSATONETTO,    
															DATAAGGIORNAMENTO,
															CODICEFASCIARENDIMENTO,
															DECRIZIONEFASCIARENDIMENTO,
															SERIEBUONO,
															VALORESCADENZALORDO,
															FLAGNETTISTALORDISTA,
															IMPORTONETTO,
															VALORESCADENZANETTO,
															VALORENOMINALE,
															DATASOTTOSCRIZIONE,
															DATASCADENZA,
															TMSTP,             
															MOTIVO_SCARTO,     
															RIPROPONIBILE     
														)
												VALUES (RES_SCARTI_SALDI_REND_BFPD(J).CODICEBANCA,       
														RES_SCARTI_SALDI_REND_BFPD(J).CODICEAGENZIA,     
														RES_SCARTI_SALDI_REND_BFPD(J).CODICERAPPORTO,    
														RES_SCARTI_SALDI_REND_BFPD(J).CODICEINTERNO,     
														RES_SCARTI_SALDI_REND_BFPD(J).DATASALDO,         
														RES_SCARTI_SALDI_REND_BFPD(J).TIPORAPPORTO,      
														RES_SCARTI_SALDI_REND_BFPD(J).CONTROVALORE,      
														RES_SCARTI_SALDI_REND_BFPD(J).DIVISA,            
														RES_SCARTI_SALDI_REND_BFPD(J).FLAGCONSOLIDATO,   
														RES_SCARTI_SALDI_REND_BFPD(J).CTVVERSATO,        
														RES_SCARTI_SALDI_REND_BFPD(J).CTVPRELEVATO,      
														RES_SCARTI_SALDI_REND_BFPD(J).CTVVERSATONETTO,    
														RES_SCARTI_SALDI_REND_BFPD(J).DATAAGGIORNAMENTO,
														RES_SCARTI_SALDI_REND_BFPD(J).CODICEFASCIARENDIMENTO,
														RES_SCARTI_SALDI_REND_BFPD(J).DECRIZIONEFASCIARENDIMENTO,
														RES_SCARTI_SALDI_REND_BFPD(J).SERIEBUONO,
														RES_SCARTI_SALDI_REND_BFPD(J).VALORESCADENZALORDO,
														RES_SCARTI_SALDI_REND_BFPD(J).FLAGNETTISTALORDISTA,
														RES_SCARTI_SALDI_REND_BFPD(J).IMPORTONETTO,
														RES_SCARTI_SALDI_REND_BFPD(J).VALORESCADENZANETTO,
														RES_SCARTI_SALDI_REND_BFPD(J).VALORENOMINALE,
														RES_SCARTI_SALDI_REND_BFPD(J).DATASOTTOSCRIZIONE,
														RES_SCARTI_SALDI_REND_BFPD(J).DATASCADENZA,
														SYSDATE,             
														'CHIAVE PRIMARIA "id_buono_originario, CODICEINTERNO, DATASALDO" DUPLICATA',     
														'N'
														);
														
			COMMIT;
			
			FORALL J IN RES_SCARTI_SALDI_REND_BFPD.FIRST .. RES_SCARTI_SALDI_REND_BFPD.LAST
			
			DELETE /*+ nologging */  FROM TMP_PFSALDISTORICI TMP_DEL
			WHERE TMP_DEL.ROWID = RES_SCARTI_SALDI_REND_BFPD(J).ROWID;
				
				        
			        COMMIT;		        
	            
	             INSERT INTO OUTPUT_PRINT_TABLE VALUES (TO_NUMBER(TO_CHAR(SYSDATE,'YYYYMMDDHH24MISS')) || ' SCARTI TMP_PFSALDISTORICI PER CHIAVE id_buono_originario, CODICEINTERNO, DATASALDO) DUPLICATA: ' || I || ' RECORD');
			        
	END LOOP;
	CLOSE SCARTI_SALDI_REND_BFPD;
	
	INSERT INTO OUTPUT_PRINT_TABLE VALUES (TO_NUMBER(TO_CHAR(SYSDATE,'YYYYMMDDHH24MISS')) || ' SCARTI TMP_PFSALDISTORICI PER CHIAVE id_buono_originario, CODICEINTERNO, DATASALDO) DUPLICATA: ' || TOTALE);
	COMMIT;
END;