DECLARE

--Eliminare dalla tmp i record con causale 18
CURSOR DEL_MOV_INCASSATO_CAU IS
	SELECT /*+ parallel(8) */ SP.ROWID, SP.* 
	FROM TMP_PFMOV_INC_COASS SP
	WHERE SP.tipo_titolo = '18';

--Eliminare dalla tmp i record con rami diversi da 01, 03 e 05
CURSOR DEL_MOV_INCASSATO_RAMO IS
	SELECT /*+ parallel(8) */ SP.ROWID, SP.* 
	FROM TMP_PFMOV_INC_COASS SP
	WHERE SP.RAMO not in ('01', '03', '05');
	
--Eliminare dalla tmp i record con codice_prodotto in PRODOTTI_DA_ESCLUDERE
CURSOR DEL_MOV_INCASSATO_COD IS
	SELECT /*+ parallel(8) */ SP.ROWID, SP.* 
	FROM TMP_PFMOV_INC_COASS SP
	WHERE codice_prodotto in (select codicetitolo
							  from PRODOTTI_DA_ESCLUDERE);
							  							  
--Eliminare dalla tmp i record con data antecedente al 20171231
CURSOR DEL_MOV_INCASSATO_ANTE IS
	SELECT /*+ parallel(8) */ SP.ROWID, SP.* 
	FROM TMP_PFMOV_INC_COASS SP
	WHERE CASE WHEN (tipo_titolo IN ('01', '02') AND 
			TO_NUMBER(TO_CHAR(TO_DATE(data_effetto_titolo, 'YYYY-MM-DD'), 'YYYYMMDD')) < TO_NUMBER(TO_CHAR(TO_DATE(data_valuta, 'YYYY-MM-DD'), 'YYYYMMDD'))	)
				THEN LEAST(TO_NUMBER(TO_CHAR(TO_DATE(data_valuta, 'YYYY-MM-DD'), 'YYYYMMDD')), TO_NUMBER(TO_CHAR(TO_DATE(data_effetto_titolo, 'YYYY-MM-DD'), 'YYYYMMDD')))
				ELSE TO_NUMBER(TO_CHAR(TO_DATE(data_valuta, 'YYYY-MM-DD'), 'YYYYMMDD')) END	 < 20171231;
		
I	NUMBER(38,0) :=0;	

	
BEGIN

FOR CUR_ITEM IN DEL_MOV_INCASSATO_CAU

  LOOP

    I :=I+1;

      DELETE /*+ nologging */ FROM TMP_PFMOV_INC_COASS DEL_TMP_MOV
      WHERE DEL_TMP_MOV.ROWID = CUR_ITEM.ROWID;
  
      IF MOD(I,10000) = 0 THEN
		INSERT INTO OUTPUT_PRINT_TABLE VALUES (TO_NUMBER(TO_CHAR(SYSDATE,'YYYYMMDDHH24MISS')) || ' SCARTI TMP_PFMOV_INC_COASS CODICE CAUSALE 18 - COMMIT ON ROW: '|| I);
		COMMIT; 
	  END IF;
	  
  END LOOP;
  
INSERT INTO OUTPUT_PRINT_TABLE VALUES (TO_NUMBER(TO_CHAR(SYSDATE,'YYYYMMDDHH24MISS')) || ' SCARTI TMP_PFMOV_INC_COASS CODICE CAUSALE 18. RECORD ELIMINATI: '|| I);
	
COMMIT;

I := 0;

FOR CUR_ITEM IN DEL_MOV_INCASSATO_RAMO

  LOOP

    I :=I+1;

      DELETE /*+ nologging */ FROM TMP_PFMOV_INC_COASS DEL_TMP_MOV
      WHERE DEL_TMP_MOV.ROWID = CUR_ITEM.ROWID;
  
      IF MOD(I,10000) = 0 THEN
		INSERT INTO OUTPUT_PRINT_TABLE VALUES (TO_NUMBER(TO_CHAR(SYSDATE,'YYYYMMDDHH24MISS')) || ' SCARTI TMP_PFMOV_INC_COASS CODICE RAMO ERRATO - COMMIT ON ROW: '|| I);
		COMMIT; 
	  END IF;
	  
  END LOOP;
  
INSERT INTO OUTPUT_PRINT_TABLE VALUES (TO_NUMBER(TO_CHAR(SYSDATE,'YYYYMMDDHH24MISS')) || ' SCARTI TMP_PFMOV_INC_COASS CODICE RAMO ERRATO. RECORD ELIMINATI: '|| I);
	
COMMIT;

I := 0;

FOR CUR_ITEM IN DEL_MOV_INCASSATO_COD

  LOOP

    I :=I+1;

      DELETE /*+ nologging */ FROM TMP_PFMOV_INC_COASS DEL_TMP_MOV
      WHERE DEL_TMP_MOV.ROWID = CUR_ITEM.ROWID;
  
      IF MOD(I,10000) = 0 THEN
		INSERT INTO OUTPUT_PRINT_TABLE VALUES (TO_NUMBER(TO_CHAR(SYSDATE,'YYYYMMDDHH24MISS')) || ' SCARTI TMP_PFMOV_INC_COASS CODICE IN PRODOTTI_DA_ESCLUDERE - COMMIT ON ROW: '|| I);
		COMMIT; 
	  END IF;
	  
  END LOOP;
  
INSERT INTO OUTPUT_PRINT_TABLE VALUES (TO_NUMBER(TO_CHAR(SYSDATE,'YYYYMMDDHH24MISS')) || ' SCARTI TMP_PFMOV_INC_COASS CODICE IN PRODOTTI_DA_ESCLUDERE. RECORD ELIMINATI: '|| I);
	
COMMIT;

I := 0;

FOR CUR_ITEM IN DEL_MOV_INCASSATO_ANTE

  LOOP

    I :=I+1;

      DELETE /*+ nologging */  FROM TMP_PFMOV_INC_COASS DEL_TMP_MOV
      WHERE DEL_TMP_MOV.ROWID = CUR_ITEM.ROWID;
  
      IF MOD(I,10000) = 0 THEN
		INSERT INTO OUTPUT_PRINT_TABLE VALUES (TO_NUMBER(TO_CHAR(SYSDATE,'YYYYMMDDHH24MISS')) || ' SCARTI TMP_PFMOV_INC_COASS DATA ANTECEDENTE AL 20171231 - COMMIT ON ROW: '|| I);
		COMMIT; 
	  END IF;
	  
  END LOOP;
  
INSERT INTO OUTPUT_PRINT_TABLE VALUES (TO_NUMBER(TO_CHAR(SYSDATE,'YYYYMMDDHH24MISS')) || ' SCARTI TMP_PFMOV_INC_COASS DATA ANTECEDENTE AL 20171231. RECORD ELIMINATI: '|| I);
	
COMMIT;
		
END;      