DECLARE

CURSOR SCARTI_QUOTAZIONE IS
    SELECT /*+ parallel(8) */ SF.CODICETITOLO AS sf_codicetitolo,
    	TBL.cod_universo as tbl_cod_universo,
        TMP.ROWID,
        TMP.*
    FROM TMP_QUOTAZIONE_R3 TMP
	LEFT JOIN TBL_BRIDGE TBL
     ON tmp.codice_fondo = tbl.cod_universo
    LEFT JOIN STRUMENTOFINANZIARIO SF
     ON SF.CODICETITOLO = tbl.codicetitolo
  WHERE SF.codicetitolo IS NULL OR tbl.cod_universo IS NULL;

I 						NUMBER(38,0) :=0;
SCARTI_CODICETITOLO 	NUMBER :=0;
SCARTI_CODICETITOLO_B 	NUMBER :=0;


BEGIN

FOR CUR_ITEM IN SCARTI_QUOTAZIONE
    LOOP
        I := I+1;

	IF (CUR_ITEM.SF_CODICETITOLO IS NULL) THEN
	
	INSERT INTO TBL_SCARTI_TMP_QUOTAZIONE_R3 (	CODICE_PRODOTTO,
												CODICE_FONDO,
												DESCRIZIONE_FONDO,
												DATA_RIFERIMENTO,
												VALORE,
												TMSTP,
												RIPROPONIBILE,
												MOTIVO_SCARTO             											             
											)
									VALUES (CUR_ITEM.CODICE_PRODOTTO,
											CUR_ITEM.CODICE_FONDO,
											CUR_ITEM.DESCRIZIONE_FONDO,
											CUR_ITEM.DATA_RIFERIMENTO,
											CUR_ITEM.VALORE,
								            SYSDATE,
								            'S',
								            'CHIAVE ESTERNA "CODICETITOLO" NON CENSITA'
								       	 	);

	DELETE  /*+ nologging */ FROM TMP_QUOTAZIONE_R3 TMP_DEL 
	WHERE TMP_DEL.ROWID = CUR_ITEM.ROWID;
	
	SCARTI_CODICETITOLO := SCARTI_CODICETITOLO +1;
	
	IF MOD(I,10000) = 0 THEN
	    INSERT
	    INTO
	        OUTPUT_PRINT_TABLE VALUES( TO_NUMBER(TO_CHAR(SYSDATE,'YYYYMMDDHH24MISS')) ||' SCARTI TMP_QUOTAZIONE_R3 PER CHIAVE ESTERNA (CODICETITOLO) NON CENSITA - COMMIT ON ROW: ' || I);
		COMMIT;
	END IF;
	
	ELSE 
		INSERT INTO TBL_SCARTI_TMP_QUOTAZIONE_R3 (	CODICE_PRODOTTO,
													CODICE_FONDO,
													DESCRIZIONE_FONDO,
													DATA_RIFERIMENTO,
													VALORE,
													TMSTP,
													RIPROPONIBILE,
													MOTIVO_SCARTO             											             
											)
									VALUES (CUR_ITEM.CODICE_PRODOTTO,
											CUR_ITEM.CODICE_FONDO,
											CUR_ITEM.DESCRIZIONE_FONDO,
											CUR_ITEM.DATA_RIFERIMENTO,
											CUR_ITEM.VALORE,
								            SYSDATE,
								            'S',
								            'CHIAVE ESTERNA "TBL_BRIDGE" NON CENSITA'
								       	 	);

	DELETE  /*+ nologging */ FROM TMP_QUOTAZIONE_R3 TMP_DEL 
	WHERE TMP_DEL.ROWID = CUR_ITEM.ROWID;
	
	SCARTI_CODICETITOLO_B := SCARTI_CODICETITOLO_B +1;
	
	IF MOD(I,10000) = 0 THEN
	    INSERT
	    INTO
	        OUTPUT_PRINT_TABLE VALUES( TO_NUMBER(TO_CHAR(SYSDATE,'YYYYMMDDHH24MISS')) ||' SCARTI TMP_QUOTAZIONE_R3 PER CHIAVE ESTERNA (TBL_BRIDGE) NON CENSITA - COMMIT ON ROW: ' || I);
		COMMIT;
	END IF;
	
	END IF;

END LOOP;

INSERT INTO OUTPUT_PRINT_TABLE VALUES( TO_NUMBER(TO_CHAR(SYSDATE,'YYYYMMDDHH24MISS')) ||' SCARTI TMP_QUOTAZIONE_R3 PER CHIAVE ESTERNA (CODICETITOLO) NON CENSITA. RECORD ELABORATI: '|| I);
INSERT INTO OUTPUT_PRINT_TABLE VALUES(TO_NUMBER(TO_CHAR(SYSDATE,'YYYYMMDDHH24MISS')) || ' SCARTI TMP_QUOTAZIONE_R3 PER CHIAVE ESTERNA (TBL_BRIDGE) NON CENSITA. RECORD SCARTATI: ' || SCARTI_CODICETITOLO_B);
INSERT INTO OUTPUT_PRINT_TABLE VALUES(TO_NUMBER(TO_CHAR(SYSDATE,'YYYYMMDDHH24MISS')) || ' SCARTI TMP_QUOTAZIONE_R3 PER CHIAVE ESTERNA (CODICETITOLO) NON CENSITA. RECORD SCARTATI: ' || SCARTI_CODICETITOLO);

COMMIT;
END;