DECLARE

--Eliminare dalla tmp i record con codicerapporto 01000000000400000, 01000000000200000
CURSOR DEL_COSTI_SERVIZIO IS
	SELECT /*+ parallel(8) */
			CS.ROWID, CS.* 
	FROM TMP_PFCOSTI_SERV CS
	WHERE CS.CODICERAPPORTO IN ('01000000000400000', '01000000000200000');

I 	NUMBER(38,0) :=0;


BEGIN
		
FOR CUR_ITEM IN DEL_COSTI_SERVIZIO

	LOOP 			
	
	 I := I+1;
	 
	DELETE /*+ nologging */ FROM TMP_PFCOSTI_SERV TMP_DEL
	WHERE TMP_DEL.ROWID = CUR_ITEM.ROWID;
					
	IF MOD(I,10000) = 0 THEN
		INSERT INTO OUTPUT_PRINT_TABLE VALUES (TO_NUMBER(TO_CHAR(SYSDATE,'YYYYMMDDHH24MISS')) || ' SCARTI TMP_PFCOSTI_SERV CODICERAPPORTO - COMMIT ON ROW: '|| I);
		COMMIT; 
	END IF;
					
	END LOOP;

INSERT INTO OUTPUT_PRINT_TABLE VALUES (TO_NUMBER(TO_CHAR(SYSDATE,'YYYYMMDDHH24MISS')) || ' SCARTI TMP_PFCOSTI_SERV CODICERAPPORTO. RECORD ELIMINATI: '|| I);
		
COMMIT;
		
END;