DECLARE

--Eliminare dalla tmp i record con rami diversi da 01, 03 e 05
CURSOR DEL_SALDI_POLIZZE IS
	SELECT /*+ parallel(8) */ SP.ROWID, SP.* 
	FROM TMP_PFSALDI_POLIZZE SP
	WHERE SP.RAMO not in ('01', '03', '05');

I 	NUMBER(38,0) :=0;


BEGIN
		
FOR CUR_ITEM IN DEL_SALDI_POLIZZE

	LOOP 			
	
	 I := I+1;
	 
	DELETE /*+ nologging */ FROM TMP_PFSALDI_POLIZZE TMP_DEL
	WHERE TMP_DEL.ROWID = CUR_ITEM.ROWID;
					
	IF MOD(I,10000) = 0 THEN
		INSERT INTO OUTPUT_PRINT_TABLE VALUES (TO_NUMBER(TO_CHAR(SYSDATE,'YYYYMMDDHH24MISS')) || ' SCARTI TMP_PFSALDI_POLIZZE CODICE RAMO ERRATO - COMMIT ON ROW: '|| I);
		COMMIT; 
	END IF;
					
	END LOOP;

INSERT INTO OUTPUT_PRINT_TABLE VALUES (TO_NUMBER(TO_CHAR(SYSDATE,'YYYYMMDDHH24MISS')) || ' SCARTI TMP_PFSALDI_POLIZZE CODICE RAMO ERRATO. RECORD ELIMINATI: '|| I);
		
COMMIT;
		
END;