DECLARE

CHECK_TBL		NUMBER(38,0):=0;


BEGIN

SELECT COUNT(*) INTO CHECK_TBL FROM ALL_TABLES WHERE UPPER(TABLE_NAME)=UPPER('MAX_SALDO_REND_SOTT_POL') AND OWNER='RENDIMPC';

	IF (CHECK_TBL = 1) THEN
		EXECUTE IMMEDIATE 'DROP TABLE RENDIMPC.MAX_SALDO_REND_SOTT_POL';
        
        EXECUTE IMMEDIATE 'CREATE TABLE RENDIMPC.MAX_SALDO_REND_SOTT_POL (	IDPTF NUMBER, 
																			CODICETITOLO VARCHAR2(255), 
																			DATA NUMBER,
																			MAXDATA_FONDO NUMBER
																  		 ) ';
	
	        COMMIT;
    
    ELSE
    
        EXECUTE IMMEDIATE 'CREATE TABLE RENDIMPC.MAX_SALDO_REND_SOTT_POL (	IDPTF NUMBER, 
																			CODICETITOLO VARCHAR2(255), 
																			DATA NUMBER,
																			MAXDATA_FONDO NUMBER
																  		 ) ';		
	
	        COMMIT;
	END IF;

END;	