SELECT sum(column_value)
FROM   TABLE(PARALLEL_SQUAD_CTV2018(CURSOR(

SELECT /*+ PARALLEL(8) */ DISTINCT SF.LIVELLO_2 																	AS TIPOSTRUM,
				R.NDG 																			AS CODICECLIENTE,
				R.CODICERAPPORTO 																AS CODICERAPPORTO,
				R.TIPO 																			AS TIPO, 
				R.SOTTORAPPORTO 																AS SOTTO_RAPPORTO,
				'07601'																			AS CODICEBANCA,
				R.CODICEAGENZIA 																AS CODICEAGENZIA,
				R.STATO 																		AS STATO,
				R.ID 																			AS IDRAPPORTO,
				R.IDPTF 																		AS IDPTF,
				SF.CODICETITOLO 																AS CODICETITOLO,
				SF.DESCRIZIONE 																	AS DESCRIZIONETITOLO,
				SALS.DATA																		AS DATASALDO,
				NVL(SALS.CTV, 0) 																AS CTV,
				ROUND(ABS(((NVL(SALS.CTV, 0)/MOVS.SOMMAMOV) - 1)), 5)							AS VARIAZIONE,
				ROUND((POWER((1 + SS.SOGLIA), ((TO_DATE((SALS.DATA), 'YYYYMMDD') - TO_DATE((MOVS.MINDATA), 'YYYYMMDD'))/365)) - 1),5)	 AS SOGLIA_PONDERATA,
				SS.SOGLIA 																		AS SOGLIA,
				SYSDATE 																		AS DATAINS,
				TO_DATE((MOVS.MINDATA), 'YYYYMMDD') 											AS DATAINIZIO,
				NVL(MOVS.SOMMAMOV, 0)															AS SOMMAMOV,
				NVL(MOVS.SOMMAMOVPOS, 0)														AS SOMMAMOVPOS,
				NVL(MOVS.SOMMAMOVNEG, 0)														AS SOMMAMOVNEG,
				TO_DATE((MOVS.MINDATA), 'YYYYMMDD')												AS MINDATA,
				TO_DATE((MOVS.MAXDATA), 'YYYYMMDD')												AS MAXDATA,
				SYSDATE 																		AS DATAAGG,
				ABS(NVL(SALS.CTV, 0) - NVL(MOVS.SOMMAMOV, 0))                                   AS DIFF_EURO
FROM SQUADRATURE_CTV_MOVS MOVS
INNER JOIN RAPPORTO R
ON R.ID = MOVS.IDRAPPORTO
INNER JOIN SQUADRATURE_CTV_SALS SALS
    ON MOVS.CODICETITOLO = SALS.CODICETITOLO
    AND R.IDPTF = SALS.IDPTF
INNER JOIN STRUMENTOFINANZIARIO SF 
	ON MOVS.CODICETITOLO = SF.CODICETITOLO
INNER JOIN SOGLIESQUAD_CTV SS 
    ON SF.LIVELLO_2 = SS.TIPOLOGIA 
WHERE SF.PERIMETRO_REND = '1'
AND MOVS.SOMMAMOV != 0
AND (TO_DATE((SALS.DATA), 'YYYYMMDD') - TO_DATE((MOVS.MINDATA), 'YYYYMMDD')) != 0
AND ABS(((NVL(SALS.CTV, 0)/MOVS.SOMMAMOV) - 1)) > (POWER((1 + SS.SOGLIA), ((TO_DATE((SALS.DATA), 'YYYYMMDD') - TO_DATE((MOVS.MINDATA), 'YYYYMMDD'))/365)) - 1)
ORDER BY R.ID, SF.CODICETITOLO, SALS.DATA
)));