SELECT sum(column_value)
FROM   TABLE(PARALLEL_SQCTV2018_DEL(CURSOR(

SELECT 	IDPTF,
			CODICETITOLO
	FROM SQUADRATURE_CTV_2018
	WHERE DATAAGG IS NOT NULL
	AND TRUNC(SYSDATE) - TRUNC(DATAAGG) >= 1
	ORDER BY IDPTF, CODICETITOLO
)));