SELECT sum(column_value)
FROM   TABLE(PARALLEL_SQUAD_CTV2018(CURSOR(

-- Squadrature per posizioni in cui ci sono i movimenti ma non ci sono i saldi
SELECT /*+ PARALLEL(8) */ DISTINCT SF.LIVELLO_2 																		AS TIPOSTRUM,
				R.NDG 																				AS CODICECLIENTE,
				R.CODICERAPPORTO 																	AS CODICERAPPORTO,
				R.TIPO 																				AS TIPO, 
				R.SOTTORAPPORTO 																	AS SOTTO_RAPPORTO,
				'07601' 																			AS CODICEBANCA,
				R.CODICEAGENZIA 																	AS CODICEAGENZIA,
				R.STATO 																			AS STATO,
				R.ID 																				AS IDRAPPORTO,
				R.IDPTF 																			AS IDPTF,
				SF.CODICETITOLO 																	AS CODICETITOLO,
				SF.DESCRIZIONE 																		AS DESCRIZIONETITOLO,
				MOVS.MAXDATA																		AS DATASALDO,
				0 																					AS CTV,
				ROUND(ABS((MOVS.SOMMAMOV/MOVS.SOMMAMOVPOS)), 5)										AS VARIAZIONE,
				ROUND((POWER((1 + SS.SOGLIA), (TO_DATE((MOVS.MAXDATA), 'YYYYMMDD') - TO_DATE((MOVS.MINDATA), 'YYYYMMDD'))/365) - 1),5)		AS SOGLIA_PONDERATA,
				SS.SOGLIA 																			AS SOGLIA,
				SYSDATE 																			AS DATAINS,
				TO_DATE((MOVS.MINDATA), 'YYYYMMDD') 												AS DATAINIZIO,
				NVL(MOVS.SOMMAMOV, 0)																AS SOMMAMOV,
				NVL(MOVS.SOMMAMOVPOS, 0)															AS SOMMAMOVPOS,
				NVL(MOVS.SOMMAMOVNEG, 0)															AS SOMMAMOVNEG,
				TO_DATE((MOVS.MINDATA), 'YYYYMMDD')													AS MINDATA,
				TO_DATE((MOVS.MAXDATA), 'YYYYMMDD')													AS MAXDATA,
				SYSDATE 																			AS DATAAGG,
				ABS(0 - NVL(MOVS.SOMMAMOV, 0))                                   					AS DIFF_EURO
FROM SQUADRATURE_CTV_MOVS MOVS
INNER JOIN RAPPORTO R
ON R.ID = MOVS.IDRAPPORTO
LEFT JOIN SALDO_REND SR
ON SR.IDPTF= R.IDPTF AND SR.CODICETITOLO = MOVS.CODICETITOLO
INNER JOIN STRUMENTOFINANZIARIO SF 
	ON MOVS.CODICETITOLO = SF.CODICETITOLO
INNER JOIN SOGLIESQUAD_CTV SS 
    ON SF.LIVELLO_2 = SS.TIPOLOGIA 
WHERE SF.PERIMETRO_REND = '1'
AND MOVS.SOMMAMOVPOS != 0
AND (TO_DATE((MOVS.MAXDATA), 'YYYYMMDD') - TO_DATE((MOVS.MINDATA), 'YYYYMMDD')) != 0
AND SR.IDPTF IS NULL
AND ABS((MOVS.SOMMAMOV/MOVS.SOMMAMOVPOS)) > (POWER((1 + SS.SOGLIA), (TO_DATE((MOVS.MAXDATA), 'YYYYMMDD') - TO_DATE((MOVS.MINDATA), 'YYYYMMDD'))/365) - 1)
ORDER BY R.ID, SF.CODICETITOLO, MOVS.MAXDATA
)));