SELECT sum(column_value)
FROM   TABLE(PARALLEL_SQUAD_CTV_del(CURSOR(

SELECT 	IDPTF,
			CODICETITOLO
	FROM SQUADRATURE_CTV
	WHERE DATAAGG IS NOT NULL
	AND TRUNC(SYSDATE) - TRUNC(DATAAGG) >= 1
	ORDER BY IDPTF, CODICETITOLO
)));