DECLARE

CURSOR CERCA_STRUMENTI IS
	SELECT   SF.CODICETITOLO, P.MOLTIPLICATORE
	FROM STRUMENTOFINANZIARIO SF
	INNER JOIN PREZZI P 
		ON SF.CODICETITOLO = P.CODICETITOLO
		AND P.DATA = (SELECT MAX(DATA)
					  FROM PREZZI PP
					  WHERE PP.CODICETITOLO = P.CODICETITOLO)
	WHERE I_MOLTIPLICATORE IS NULL;

	
BEGIN 
	
	FOR CUR_ITEM IN CERCA_STRUMENTI
		LOOP 
			UPDATE   STRUMENTOFINANZIARIO SF1
			SET SF1.I_MOLTIPLICATORE = CUR_ITEM.MOLTIPLICATORE
			WHERE SF1.CODICETITOLO = CUR_ITEM.CODICETITOLO;
					
		END LOOP;	
		
		INSERT INTO output_print_table VALUES (to_number(to_char(sysdate,'YYYYMMDDHH24MISS')) || ' UPDATE STRUMENTOFINANZIARIO.');
	COMMIT;	
	
END;