/**
* DROP INDEX
**/
DECLARE
    i INTEGER;
BEGIN

SELECT COUNT(*) INTO i FROM user_constraints WHERE constraint_name =  'TEMP_PROFILO_PK';
IF i > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE TEMP_PROFILO DROP CONSTRAINT TEMP_PROFILO_PK';
END IF;


SELECT COUNT(*) INTO i FROM user_constraints WHERE constraint_name = 'TEMP_CLIENTE_PK';
IF i > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE TEMP_CLIENTE DROP CONSTRAINT TEMP_CLIENTE_PK';
END IF;


SELECT COUNT(*) INTO i FROM user_constraints WHERE constraint_name = 'TEMP_RAPPORTO_PK';
IF i > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE TEMP_RAPPORTO DROP CONSTRAINT TEMP_RAPPORTO_PK';
END IF;


SELECT COUNT(*) INTO i FROM user_constraints WHERE constraint_name = 'TEMP_RAPPORTO_BFP_PK';
IF i > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE RENDIMPC.TEMP_RAPPORTO_BFP DROP CONSTRAINT TEMP_RAPPORTO_BFP_PK';
END IF;

SELECT COUNT(*) INTO i FROM user_indexes WHERE index_name = 'TMP_RAPPORTO_IDX_BFP';
IF i > 0 THEN
    EXECUTE IMMEDIATE 'DROP INDEX TMP_RAPPORTO_IDX_BFP ';
END IF;


SELECT COUNT(*) INTO i FROM user_constraints WHERE constraint_name = 'TEMP_DELTARAPPORTO_PK';
IF i > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE TEMP_DELTARAPPORTO DROP CONSTRAINT TEMP_DELTARAPPORTO_PK';
END IF;


SELECT COUNT(*) INTO i FROM USER_INDEXES WHERE INDEX_NAME =  'PTF_CODICE_IDX';
IF i > 0 THEN
    EXECUTE IMMEDIATE 'DROP INDEX PTF_CODICE_IDX';
END IF;


SELECT COUNT(*) INTO i FROM USER_INDEXES WHERE INDEX_NAME =  'PFRAP_NDG_IDX';
IF i > 0 THEN
    EXECUTE IMMEDIATE 'DROP INDEX PFRAP_NDG_IDX';
END IF;


SELECT COUNT(*) INTO i FROM USER_INDEXES WHERE INDEX_NAME =  'TEMP_PTF_CODICE_IDX';
IF i > 0 THEN
    EXECUTE IMMEDIATE 'DROP INDEX TEMP_PTF_CODICE_IDX';
END IF;


SELECT COUNT(*) INTO i FROM USER_INDEXES WHERE INDEX_NAME =  'RAPP_NDG_IDX';
IF i = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX RAPP_NDG_IDX ON RAPPORTO (NDG) TABLESPACE RENDIMPC_INDEX PARALLEL 8';
				        EXECUTE IMMEDIATE 'ALTER INDEX RAPP_NDG_IDX NOPARALLEL';
END IF;


SELECT COUNT(*) INTO i FROM USER_INDEXES WHERE INDEX_NAME =  'RAPP_NDGC_IDX';
IF i = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX RAPP_NDGC_IDX ON RAPPORTO (NDGC) TABLESPACE RENDIMPC_INDEX PARALLEL 8';
				        EXECUTE IMMEDIATE 'ALTER INDEX RAPP_NDGC_IDX NOPARALLEL';
END IF;


SELECT COUNT(*) INTO i FROM USER_INDEXES WHERE INDEX_NAME =  'RAP_PTF_IDX';
IF i = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX RAP_PTF_IDX ON RAPPORTO(IDPTF) TABLESPACE RENDIMPC_INDEX PARALLEL 8';
				        EXECUTE IMMEDIATE 'ALTER INDEX RAPPORTO NOPARALLEL';
END IF;


SELECT COUNT(*) INTO i FROM USER_INDEXES WHERE INDEX_NAME =  'TEMP_SALDI_IDX';
IF i > 0 THEN
    EXECUTE IMMEDIATE 'DROP INDEX TEMP_SALDI_IDX';
END IF;


SELECT COUNT(*) INTO i FROM USER_INDEXES WHERE INDEX_NAME =  'RAPP_TMPSAL_IDX';
IF i > 0 THEN
    EXECUTE IMMEDIATE 'DROP INDEX RAPP_TMPSAL_IDX';
END IF;


SELECT COUNT(*) INTO i FROM USER_INDEXES WHERE INDEX_NAME =  'TMP_GMPOL1_IDX';
IF i > 0 THEN
    EXECUTE IMMEDIATE 'DROP INDEX TMP_GMPOL1_IDX';
END IF;


SELECT COUNT(*) INTO i FROM USER_INDEXES WHERE INDEX_NAME =  'TMP_GMPOL2_IDX';
IF i > 0 THEN
    EXECUTE IMMEDIATE 'DROP INDEX TMP_GMPOL2_IDX';
END IF;


SELECT COUNT(*) INTO i FROM USER_INDEXES WHERE INDEX_NAME =  'TMP_RAMOPOL_IDX';
IF i > 0 THEN
    EXECUTE IMMEDIATE 'DROP INDEX TMP_RAMOPOL_IDX';
END IF;


SELECT COUNT(*) INTO i FROM USER_INDEXES WHERE INDEX_NAME =  'TMP_SALDOCODICETIT_IDX';
IF i > 0 THEN
    EXECUTE IMMEDIATE 'DROP INDEX TMP_SALDOCODICETIT_IDX';
END IF;


SELECT COUNT(*) INTO i FROM USER_INDEXES WHERE INDEX_NAME =  'TMP_IX_CLI_INT';
IF i > 0 THEN
    EXECUTE IMMEDIATE 'DROP INDEX TMP_IX_CLI_INT';
END IF;


SELECT COUNT(*) INTO i FROM USER_INDEXES WHERE INDEX_NAME =  'TMP_IX_PTFD_CLI';
IF i = 1 THEN
    EXECUTE IMMEDIATE 'DROP INDEX TMP_IX_PTFD_CLI';
END IF;


SELECT COUNT(*) INTO i FROM USER_INDEXES WHERE INDEX_NAME =  'TMP_IX_NDG_CLI';
IF i = 1 THEN
    EXECUTE IMMEDIATE 'DROP INDEX TMP_IX_NDG_CLI';
END IF;


SELECT COUNT(*) INTO i FROM USER_INDEXES WHERE INDEX_NAME =  'TMP_IX_NDGCLUSTER_TEMCLI';
IF i = 1 THEN
    EXECUTE IMMEDIATE 'DROP INDEX TMP_IX_NDGCLUSTER_TEMCLI';
END IF;


SELECT COUNT(*) INTO i FROM USER_INDEXES WHERE INDEX_NAME =  'TMP_IX_PRF_TEMPRF';
IF i = 1 THEN
    EXECUTE IMMEDIATE 'DROP INDEX TMP_IX_PRF_TEMPRF';
END IF;


SELECT COUNT(*) INTO i FROM USER_INDEXES WHERE INDEX_NAME = 'TEMP_IDX_TMP_RAP';
IF i = 1 THEN
    EXECUTE IMMEDIATE 'DROP INDEX TEMP_IDX_TMP_RAP';
END IF;


--SELECT COUNT(*) INTO i FROM user_constraints WHERE constraint_name = 'NDG_PK';
--IF i =0 THEN
--    EXECUTE IMMEDIATE 'ALTER TABLE RENDIMPC.NDG ADD CONSTRAINT NDG_PK PRIMARY KEY (CODICEBANCA,NDG) USING INDEX TABLESPACE RENDIMPC_INDEX';
--END IF;


SELECT COUNT(*) INTO i FROM user_constraints WHERE constraint_name = 'RAPP_FK_NDG';
IF i =0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE RENDIMPC.RAPPORTO ADD CONSTRAINT RAPP_FK_NDG FOREIGN KEY (NDG,CODICEBANCA) REFERENCES  NDG (NDG,CODICEBANCA)';
END IF;


SELECT COUNT(*) INTO i FROM user_constraints WHERE constraint_name = 'RAPP_FK_IDPTF';
IF i =0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE RENDIMPC.RAPPORTO ADD CONSTRAINT RAPP_FK_IDPTF FOREIGN KEY (IDPTF) REFERENCES  PORTAFOGLIO (ID)';
END IF;


SELECT COUNT(*) INTO i FROM user_constraints WHERE constraint_name = 'SF_PK';
IF i =1 THEN
    EXECUTE IMMEDIATE'ALTER TABLE RENDIMPC.STRUMENTOFINANZIARIO ENABLE VALIDATE CONSTRAINT SF_PK';
END IF;

SELECT COUNT(*) INTO i FROM user_constraints WHERE constraint_name = 'FK_MOVIMENTO_TERZO_CODICE';
IF i =1 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE RENDIMPC.MOVIMENTO_RAMO_TERZO ENABLE NOVALIDATE CONSTRAINT FK_MOVIMENTO_TERZO_CODICE';
END IF;

SELECT COUNT(*) INTO i FROM user_constraints WHERE constraint_name = 'FK_COSTO_POS_SF';
IF i =1 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE RENDIMPC.COSTO_POSIZIONE ENABLE NOVALIDATE CONSTRAINT FK_COSTO_POS_SF';
END IF;

SELECT COUNT(*) INTO i FROM user_constraints WHERE constraint_name = 'FK_MOVIMENTO_CODICETITOLO';
IF i =1 THEN
	execute immediate 'ALTER TABLE RENDIMPC.MOVIMENTO ENABLE NOVALIDATE CONSTRAINT FK_MOVIMENTO_CODICETITOLO';
END IF;
		

SELECT COUNT(*) INTO i FROM user_constraints WHERE constraint_name = 'FK_SALDO_REND_STRUMENTOFINANZI';
IF i =1 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE RENDIMPC.saldo_rend ENABLE NOVALIDATE CONSTRAINT FK_SALDO_REND_STRUMENTOFINANZI';
END IF;
						  
						  
SELECT COUNT(*) INTO i FROM user_constraints WHERE constraint_name = 'FK_SALDO_REND_PORTAFOGLIO';
IF i =1 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE RENDIMPC.saldo_rend ENABLE NOVALIDATE CONSTRAINT FK_SALDO_REND_PORTAFOGLIO';
END IF;


SELECT COUNT(*) INTO i FROM user_constraints WHERE constraint_name = 'FK_SERIE_STORICA_SF';
IF i =0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE RENDIMPC.serie_storica ADD CONSTRAINT FK_SERIE_STORICA_SF FOREIGN KEY (codicetitolo) REFERENCES strumentofinanziario (codicetitolo)';
END IF;


SELECT COUNT(*) INTO i FROM USER_INDEXES WHERE INDEX_NAME = 'TEMP_RAP_IDX_TIPO';
IF i = 1 THEN
    EXECUTE IMMEDIATE 'DROP INDEX RENDIMPC.TEMP_RAP_IDX_TIPO';
END IF;


SELECT COUNT(*) INTO i FROM USER_INDEXES WHERE INDEX_NAME = 'TEMP_RAP_IDX_BUONO';
IF i = 1 THEN
    EXECUTE IMMEDIATE 'DROP INDEX RENDIMPC.TEMP_RAP_IDX_BUONO';
END IF;


SELECT COUNT(*) INTO i FROM USER_INDEXES WHERE INDEX_NAME = 'TEMP_RAP_IDX_MERGE_PZ';
IF i = 1 THEN
    EXECUTE IMMEDIATE 'DROP INDEX RENDIMPC.TEMP_RAP_IDX_MERGE_PZ';
END IF;



SELECT COUNT(*) INTO i FROM user_indexes WHERE index_name = 'TMP_IX_RAP_SOSP';
IF i = 1 THEN
	EXECUTE IMMEDIATE 'DROP INDEX TMP_IX_RAP_SOSP';
END IF;


SELECT COUNT(*) INTO i FROM user_indexes WHERE index_name = 'TMP_SAL_IDX_J';
IF i = 1 THEN
	EXECUTE IMMEDIATE 'DROP INDEX TMP_SAL_IDX_J';
END IF;
COMMIT;


SELECT COUNT(*) INTO i FROM user_indexes WHERE index_name = 'TEMP_RAP_IDX_DELTA';
IF i = 1 THEN
    EXECUTE IMMEDIATE 'DROP INDEX RENDIMPC.TEMP_RAP_IDX_DELTA';
END IF;


SELECT COUNT(*) INTO i FROM user_indexes WHERE index_name = 'SALDI_PK';
IF i = 0 THEN
	EXECUTE IMMEDIATE 'ALTER TABLE SALDO ADD CONSTRAINT SALDI_PK PRIMARY KEY (IDPTF, CODICETITOLO, DATA) USING INDEX TABLESPACE RENDIMPC_INDEX';
END IF;	

SELECT COUNT(*) INTO i FROM user_indexes WHERE index_name = 'IDX_RAP_SCARTI';
	IF i = 1 THEN
	    EXECUTE IMMEDIATE 'DROP INDEX RENDIMPC.IDX_RAP_SCARTI';
	END IF; 

END;