DECLARE
    i INTEGER;
BEGIN
    SELECT COUNT(*) INTO i FROM user_indexes WHERE index_name = 'RAPP_NDG_IDX';
    IF i = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX RAPP_NDG_IDX ON RAPPORTO (NDG) TABLESPACE RENDIMPC_INDEX PARALLEL 8';
        EXECUTE IMMEDIATE 'ALTER INDEX RAPP_NDG_IDX NOPARALLEL';
    END IF;

    SELECT COUNT(*) INTO i FROM user_indexes WHERE index_name = 'RAPPORTO_IDX';
    IF i = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX RAPPORTO_IDX ON RAPPORTO(NDG,CODICERAPPORTO,CODICEAGENZIA) TABLESPACE RENDIMPC_INDEX PARALLEL 8';
        EXECUTE IMMEDIATE 'ALTER INDEX RAPPORTO_IDX NOPARALLEL';
    END IF;
END;
