DECLARE
	i INTEGER;
	BEGIN
	
		MERGE /*+APPEND NOLOGGING PARALLEL(8)*/ INTO ANAGRAFICA_FILIALI A 
		USING( SELECT CODICEBANCA, DESCRIZIONEBANCA, CODICEAGENZIA, DESCRIZIONEAGENZIA, CODICEFILIALE, DESCRIZIONEFILIALE, CODICEAREATERR, 
		        DESCRIZIONEAREATERR, CODICEREGIONE, DESCRIZIONEREGIONE, CODICEUFFICIO, TURNOSTABILENAUTILUS, STATO, RUOLOMASTER, TIPOLOGIAUPCANALE, 
		        INDIRIZZO, CAP, COMUNE, PROVINCIA FROM TMP_PFSTRUTT) T
		ON (T.CODICEAGENZIA=A.CODICEAGENZIA)
		WHEN NOT MATCHED THEN 
		INSERT (COD_BANCA, DESC_BANCA, CODICEAGENZIA, DESC_AGENZIA, FILIALE, DESC_FILIALE, AREA_TERR, 
			DESC_AREA_TERR, ID_REGIONE, REGIONE, TIPO_UFFICIO, TURNO_STABILE, STATO, RUOLO_MASTER, TIPOLOGIA_UP, INDIRIZZO, CAP, COMUNE, PROVINCIA)
		VALUES (T.CODICEBANCA, T.DESCRIZIONEBANCA, T.CODICEAGENZIA, T.DESCRIZIONEAGENZIA,T. CODICEFILIALE, T.DESCRIZIONEFILIALE, T.CODICEAREATERR, 
		T.DESCRIZIONEAREATERR, T.CODICEREGIONE, T.DESCRIZIONEREGIONE, T.CODICEUFFICIO, T.TURNOSTABILENAUTILUS, T.STATO, T.RUOLOMASTER, T.TIPOLOGIAUPCANALE, 
		T.INDIRIZZO, T.CAP, T.COMUNE, T.PROVINCIA);
		COMMIT;


		SELECT COUNT(*) INTO i FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'PK_ANAGFI';
		IF i = 0 THEN
			EXECUTE IMMEDIATE 'ALTER TABLE ANAGRAFICA_FILIALI ADD CONSTRAINT PK_ANAGFI PRIMARY KEY(CODICEAGENZIA) USING INDEX TABLESPACE RENDIMPC_INDEX';
		END IF;

----------

		COMMIT;

		MERGE /*+APPEND NOLOGGING PARALLEL(GESTORE_RENDICONTO,8)*/ INTO GESTORE_RENDICONTO G
		USING (SELECT UP,GESTORE,QUALIFICA,NR_PIANIFICATI,NR_SVOLTI,
			CONCAT(CONCAT(SUBSTR(DATA_INIZIO,7,4),SUBSTR(DATA_INIZIO,4,2)),SUBSTR(DATA_INIZIO,1,2)) DI,
			CONCAT(CONCAT(SUBSTR(DATA_FINE,7,4),SUBSTR(DATA_FINE,4,2)),SUBSTR(DATA_FINE,1,2)) DF,
			COGNOME, NOME, CELLULARE
		FROM TMP_PFGERARCHIA) T
		ON (T.GESTORE=G.GESTORE)
		WHEN NOT MATCHED THEN 
		INSERT (UP, GESTORE, QUALIFICA, NR_PIANIFICATI, NR_SVOLTI, DATA_INIZIO, DATA_FINE, COGNOME, NOME, CELLULARE)
		VALUES(T.UP, T.GESTORE, T.QUALIFICA, T.NR_PIANIFICATI, T.NR_SVOLTI, T.DI, T.DF,	T.COGNOME, T.NOME, T.CELLULARE);
		
		COMMIT;

		SELECT COUNT(*) INTO i FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'PK_GEST';
		IF i = 0 THEN
			EXECUTE IMMEDIATE 'ALTER TABLE GESTORE_RENDICONTO ADD CONSTRAINT PK_GEST PRIMARY KEY(UP,GESTORE) USING INDEX TABLESPACE RENDIMPC_INDEX';
		END IF;
	END;