DECLARE i INTEGER;

BEGIN
	
SELECT COUNT(*) INTO i FROM user_indexes WHERE index_name = 'TEMP_RAP_IDX_TIPO';
IF i = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX RENDIMPC.TEMP_RAP_IDX_TIPO ON TMP_PFRAP(TIPORAPPORTO) TABLESPACE RENDIMPC_INDEX PARALLEL 8';
			EXECUTE IMMEDIATE 'ALTER INDEX TEMP_RAP_IDX_TIPO NOPARALLEL';
END IF;


SELECT COUNT(*) INTO i FROM user_indexes WHERE index_name = 'TEMP_RAP_IDX_BUONO';
IF i = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX RENDIMPC.TEMP_RAP_IDX_BUONO ON TMP_PFRAP(ID_BUONO_ORIGINARIO) TABLESPACE RENDIMPC_INDEX PARALLEL 8';
			EXECUTE IMMEDIATE 'ALTER INDEX TEMP_RAP_IDX_BUONO NOPARALLEL';
END IF;

dbms_stats.gather_table_stats(ownname => sys_context('USERENV', 'CURRENT_SCHEMA'), tabname => 'TMP_PFRAP', degree => 4, estimate_percent=>1);
   

END;



