TRUNCATE TABLE PROFILORISCHIO DROP STORAGE;

INSERT /*+APPEND NOLOGGING PARALLEL(8)*/INTO PROFILORISCHIO P (P.ID, P.NDG,P.CODICEBANCA,P.OBIETTIVO,P.ESPERIENZA,P.HPPERC1,P.HPPERC2,P.HPPERC3,P.HPPERC4,P.HPPERC5,P.I1,P.FREQ1,P.CONOSCENZA_021,P.CONOSCENZA_022,P.TIPO,P.CONOSCENZA_023 )
SELECT ID_PROFILORISCHIO_SEQ.nextval, T.NDG,T.CODICEBANCA,T.RISCHIO,T.PROFILOESPCON,T.HP1,T.HP2,T.HP3,T.HP4,T.HP5,T.DATASCADENZAQUESTIONARIO,T.CONTATOREFREQUENZA,T.CONSULENZA,T.QUESTIONARIOATTIVO,T.CODICECLASSIFICAZIONEMIFID,T.SITFIN
FROM TEMP_PROFILO T where exists (SELECT 1 FROM TMP_PFANANDG C WHERE T.NDG=C.NDG); 

COMMIT;