INSERT /*+APPEND NOLOGGING PARALLEL(8)*/ INTO RAPPORTO (CODICEBANCA,CODICERAPPORTO,NDG,CODICEAGENZIA,TIPO,SOTTORAPPORTO,STATO,NDGC,ID,IDPTF,DATAACCENSIONE,ID_BUONO_ORIGINARIO,DATAINIZIO)
SELECT CODICEBANCA,CODICERAPPORTO,NDG,CODICEAGENZIA,TIPORAPPORTO,C_SOTTORAPPORTO,'A', NDG, ID, IDPTF, DT_APERTURA,ID_BUONO_ORIGINARIO,CURRENT_TIMESTAMP
FROM TEMP_DELTARAPPORTO;
