DECLARE i INTEGER;

BEGIN
	
SELECT COUNT(*) INTO i FROM user_indexes WHERE index_name = 'TEMP_RAP_IDX_MERGE_PZ';
IF i = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX RENDIMPC.TEMP_RAP_IDX_MERGE_PZ ON TEMP_RAPPORTO_PZ_MERGE(NDG, CODICERAPPORTO, TIPORAPPORTO, CODICEAGENZIA) TABLESPACE RENDIMPC_INDEX PARALLEL 8';
	EXECUTE IMMEDIATE 'ALTER INDEX TEMP_RAP_IDX_MERGE_PZ NOPARALLEL';
END IF;

dbms_stats.gather_table_stats(ownname => sys_context('USERENV', 'CURRENT_SCHEMA'), tabname => 'TEMP_RAPPORTO_PZ_MERGE', degree => 4, estimate_percent=>1);


EXECUTE IMMEDIATE 'MERGE /*+APPEND NOLOGGING PARALLEL(8)*/ INTO RAPPORTO R
					USING(SELECT NDG, CODICERAPPORTO, TIPORAPPORTO, CODICEAGENZIA FROM TEMP_RAPPORTO_PZ_MERGE) T
					ON (R.CODICERAPPORTO=T.CODICERAPPORTO AND R.TIPO=T.TIPORAPPORTO)
					WHEN MATCHED THEN UPDATE SET R.NDG=T.NDG, R.CODICEAGENZIA=T.CODICEAGENZIA, R.DATAMODIFICA=CURRENT_TIMESTAMP, R.NDGC=T.NDG';

END;



