DECLARE 

i INTEGER;

BEGIN
	
	SELECT COUNT(*) INTO i FROM user_indexes WHERE index_name = 'TMP_IX_RAP_SOSP';
  	IF i = 0 THEN
   	 EXECUTE IMMEDIATE 'CREATE INDEX TMP_IX_RAP_SOSP ON RAPPORTO(NDG,CODICERAPPORTO,TIPO) TABLESPACE RENDIMPC_INDEX  PARALLEL 8';
			EXECUTE IMMEDIATE 'ALTER INDEX TMP_IX_RAP_SOSP NOPARALLEL';
  	END IF;
	
	MERGE /*+APPEND NOLOGGING PARALLEL(8)*/ INTO RAPPORTO R
	USING (SELECT NDG,CODICERAPPORTO,TIPO FROM RAPPORTO
	       MINUS
	       SELECT NDG,CODICERAPPORTO,TIPORAPPORTO FROM TEMP_RAPPORTO) T
    ON (R.NDG=T.NDG
       AND R.CODICERAPPORTO=T.CODICERAPPORTO
	   AND R.TIPO=T.TIPO)
	WHEN MATCHED THEN
	UPDATE SET R.STATO='S',DATAFINE=CURRENT_TIMESTAMP,DATAMODIFICA=CURRENT_TIMESTAMP;

	COMMIT;
	
	SELECT COUNT(*) INTO i FROM user_indexes WHERE index_name = 'TMP_IX_RAP_SOSP';
  	IF i = 1 THEN
   	 EXECUTE IMMEDIATE 'DROP INDEX TMP_IX_RAP_SOSP';
  	END IF;
END;

