DECLARE
    i INTEGER;
BEGIN

    SELECT COUNT(*) INTO i FROM user_indexes WHERE index_name = 'TMP_RAPPORTO_IDX_BFP';
    IF i = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX TMP_RAPPORTO_IDX_BFP ON RAPPORTO(NDG,ID_BUONO_ORIGINARIO,CODICERAPPORTO) TABLESPACE RENDIMPC_INDEX  PARALLEL 8';
		EXECUTE IMMEDIATE 'ALTER INDEX TMP_RAPPORTO_IDX_BFP NOPARALLEL';
    END IF;
    
    COMMIT;
    
	MERGE /*+APPEND NOLOGGING PARALLEL(8)*/ INTO RAPPORTO R
	USING(SELECT NDG, ID_BUONO_ORIGINARIO, CODICEAGENZIA, CODICERAPPORTO FROM TEMP_RAPPORTO_BFP) T
	ON (R.ID_BUONO_ORIGINARIO=T.ID_BUONO_ORIGINARIO AND R.ID_BUONO_ORIGINARIO IS NOT NULL AND (R.CODICERAPPORTO<>T.CODICERAPPORTO OR R.NDG<>T.NDG))
	WHEN MATCHED THEN UPDATE SET R.CODICERAPPORTO=T.CODICERAPPORTO, R.CODICEAGENZIA=T.CODICEAGENZIA, R.NDG=T.NDG, R.DATAMODIFICA=CURRENT_TIMESTAMP, R.NDGC=T.NDG;
	
	COMMIT;

	
    SELECT COUNT(*) INTO I FROM USER_INDEXES WHERE INDEX_NAME = 'TMP_RAPPORTO_IDX_BFP';
    IF i = 1 THEN
        EXECUTE IMMEDIATE 'DROP INDEX TMP_RAPPORTO_IDX_BFP ';
    END IF;
    
END;