DECLARE
    i INTEGER;
BEGIN

	EXECUTE IMMEDIATE 'TRUNCATE TABLE TEMP_MULTIRAMO DROP STORAGE';
	COMMIT;
	
	INSERT /*+APPEND NOLOGGING PARALLEL(8)*/ into TEMP_MULTIRAMO(CODICETITOLO,CODICERAMO)
	(
		SELECT DISTINCT A.CODICETITOLO,A.GMPOL11 FROM (
		(SELECT CODICETITOLO,GMPOL11,VAR FROM STRUMENTOFINANZIARIO WHERE RAMOPOL IN ('M','N') AND GMPOL11 IS NOT NULL) A
		JOIN
		(SELECT GMPOL11,MAX(VAR) AS MAXVAR FROM STRUMENTOFINANZIARIO WHERE RAMOPOL IN ('M','N') AND GMPOL11 IS NOT NULL GROUP BY GMPOL11) B
		ON A.GMPOL11=B.GMPOL11
		AND A.VAR=B.MAXVAR
		)
	UNION
	
		SELECT DISTINCT A.CODICETITOLO,A.GMPOL12 FROM (
		(SELECT CODICETITOLO,GMPOL12,VAR FROM STRUMENTOFINANZIARIO WHERE RAMOPOL IN ('M','N') AND GMPOL12 IS NOT NULL) A
		JOIN
		(SELECT GMPOL12,MAX(VAR) AS MAXVAR FROM STRUMENTOFINANZIARIO WHERE RAMOPOL IN ('M','N') AND GMPOL12 IS NOT NULL GROUP BY GMPOL12) B
		ON A.GMPOL12=B.GMPOL12
		AND A.VAR=B.MAXVAR
		)
	);
	COMMIT;


    SELECT COUNT(*) INTO i FROM user_indexes WHERE index_name = 'TMP_GMPOL1_IDX';
    IF i = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX TMP_GMPOL1_IDX ON STRUMENTOFINANZIARIO(GMPOL11) TABLESPACE RENDIMPC_INDEX ';
    END IF;
    
    SELECT COUNT(*) INTO i FROM user_indexes WHERE index_name = 'TMP_GMPOL2_IDX';
	IF i = 0 THEN
	      EXECUTE IMMEDIATE 'CREATE INDEX TMP_GMPOL2_IDX ON STRUMENTOFINANZIARIO(GMPOL12) TABLESPACE RENDIMPC_INDEX ';
	END IF;

    SELECT COUNT(*) INTO i FROM user_indexes WHERE index_name = 'TMP_RAMOPOL_IDX';
    IF i = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX TMP_RAMOPOL_IDX ON STRUMENTOFINANZIARIO(RAMOPOL) TABLESPACE RENDIMPC_INDEX ';
    END IF;	
    
    SELECT COUNT(*) INTO i FROM user_indexes WHERE index_name = 'TMP_SALDOCODICETIT_IDX';
    IF i = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX TMP_SALDOCODICETIT_IDX ON SALDO(CODICETITOLO) TABLESPACE RENDIMPC_INDEX ';
    END IF;    
    
    dbms_stats.gather_table_stats(ownname => sys_context('USERENV', 'CURRENT_SCHEMA'), tabname => 'TEMP_MULTIRAMO', degree => 4, estimate_percent=>1);
    dbms_stats.gather_table_stats(ownname => sys_context('USERENV', 'CURRENT_SCHEMA'), tabname => 'SALDO', degree => 4, estimate_percent=>1);
    
	
	UPDATE /*+ APPEND PARALLEL*/ SALDO SET CODICETITOLO=(SELECT MAX(CODICETITOLO) FROM TEMP_MULTIRAMO T WHERE SALDO.CODICETITOLO=T.CODICERAMO)
	WHERE EXISTS (
		SELECT 1 FROM STRUMENTOFINANZIARIO WHERE RAMOPOL IN ('M','N') and (SALDO.CODICETITOLO=GMPOL11 OR SALDO.CODICETITOLO=GMPOL12)
	);
	
	EXECUTE IMMEDIATE 'TRUNCATE TABLE PFPPROCESS_DATA DROP STORAGE';
END;
