DECLARE

CURSOR SCARTI_RAPPORTI_DOPPI IS
	SELECT   TMP.ROWID, TMP.* 
	FROM TMP_PFRAP TMP
	INNER JOIN (SELECT NDG,CODICERAPPORTO,TIPORAPPORTO
		  FROM TMP_PFRAP TMP
		  WHERE ID_BUONO_ORIGINARIO IS NULL
		  GROUP BY NDG,CODICERAPPORTO,TIPORAPPORTO
		  HAVING COUNT(*) >1) A
	ON TMP.NDG = A.NDG
		AND TMP.CODICERAPPORTO=A.CODICERAPPORTO
		AND TMP.TIPORAPPORTO=A.TIPORAPPORTO;

TYPE SCARTI_RAPPORTI_DOPPI_TYPE IS TABLE OF SCARTI_RAPPORTI_DOPPI%ROWTYPE INDEX BY PLS_INTEGER;

RES_SCARTI_RAPPORTI_DOPPI SCARTI_RAPPORTI_DOPPI_TYPE;

ROWS      PLS_INTEGER := 10000;
        
I 				NUMBER(38,0);
TOTALE			NUMBER(38,0):=0;
CHECK_IDX		NUMBER(38,0):=0;


BEGIN
	
	SELECT COUNT(*) INTO CHECK_IDX FROM user_indexes WHERE index_name = 'IDX_RAP_SCARTI';
	IF CHECK_IDX = 0 THEN
	    EXECUTE IMMEDIATE 'CREATE INDEX RENDIMPC.IDX_RAP_SCARTI ON TMP_PFRAP(NDG,CODICERAPPORTO,TIPORAPPORTO) TABLESPACE RENDIMPC_INDEX PARALLEL 8';
			EXECUTE IMMEDIATE 'ALTER INDEX IDX_RAP_SCARTI NOPARALLEL';
	END IF; 
	
	
	OPEN SCARTI_RAPPORTI_DOPPI;
	LOOP
			FETCH SCARTI_RAPPORTI_DOPPI BULK COLLECT INTO RES_SCARTI_RAPPORTI_DOPPI LIMIT ROWS;
				EXIT WHEN RES_SCARTI_RAPPORTI_DOPPI.COUNT = 0;  
				
	      I:=0;
	      I:= RES_SCARTI_RAPPORTI_DOPPI.COUNT;
	      TOTALE := TOTALE + I;
				
				FORALL J IN RES_SCARTI_RAPPORTI_DOPPI.FIRST .. RES_SCARTI_RAPPORTI_DOPPI.LAST		
	
				INSERT   INTO TBL_SCARTI_TMP_PFRAP (	CODICEAGENZIA,
														CODICEBANCA,
														CODICERAPPORTO,
														C_SOTTORAPPORTO,
														DT_APERTURA,
														DT_CHIUSURA,
														ID_BUONO_ORIGINARIO,
														NDG,
														NDG_SECONDARIO,
														PERIMETRO,
														STATO,
														TIPORAPPORTO,
														MOTIVO_SCARTO,
														TMSTP 
														)
												VALUES (RES_SCARTI_RAPPORTI_DOPPI(J).CODICEAGENZIA,
														RES_SCARTI_RAPPORTI_DOPPI(J).CODICEBANCA,
														RES_SCARTI_RAPPORTI_DOPPI(J).CODICERAPPORTO,
														RES_SCARTI_RAPPORTI_DOPPI(J).C_SOTTORAPPORTO,
														RES_SCARTI_RAPPORTI_DOPPI(J).DT_APERTURA,
														RES_SCARTI_RAPPORTI_DOPPI(J).DT_CHIUSURA,
														RES_SCARTI_RAPPORTI_DOPPI(J).ID_BUONO_ORIGINARIO,
														RES_SCARTI_RAPPORTI_DOPPI(J).NDG,
														RES_SCARTI_RAPPORTI_DOPPI(J).NDG_SECONDARIO,
														RES_SCARTI_RAPPORTI_DOPPI(J).PERIMETRO,
														RES_SCARTI_RAPPORTI_DOPPI(J).STATO,
														RES_SCARTI_RAPPORTI_DOPPI(J).TIPORAPPORTO,
														'CHIAVE PRIMARIA "NDG, CODICERAPPORTO, TIPORAPPORTO" DUPLICATA',
														SYSDATE
														);
				
			        COMMIT;		
			        
			        FORALL J IN RES_SCARTI_RAPPORTI_DOPPI.FIRST .. RES_SCARTI_RAPPORTI_DOPPI.LAST
			        	
			        DELETE   FROM TMP_PFRAP TMP_DEL
					WHERE TMP_DEL.ROWID = RES_SCARTI_RAPPORTI_DOPPI(J).ROWID;
					
					COMMIT;
			        	
	            
	             INSERT INTO OUTPUT_PRINT_TABLE VALUES (TO_NUMBER(TO_CHAR(SYSDATE,'YYYYMMDDHH24MISS')) || ' SCARTI TMP_PFRAP PER CHIAVE (NDG,CODICERAPPORTO,TIPORAPPORTO) DUPLICATA: ' || I || ' RECORD');
			        
	END LOOP;
	CLOSE SCARTI_RAPPORTI_DOPPI;
	
	INSERT INTO OUTPUT_PRINT_TABLE VALUES (TO_NUMBER(TO_CHAR(SYSDATE,'YYYYMMDDHH24MISS')) || ' SCARTI TMP_PFRAP PER CHIAVE (NDG,CODICERAPPORTO,TIPORAPPORTO) DUPLICATA: ' || TOTALE);
	COMMIT;
	
	SELECT COUNT(*) INTO CHECK_IDX FROM user_indexes WHERE index_name = 'IDX_RAP_SCARTI';
	IF CHECK_IDX = 1 THEN
	    EXECUTE IMMEDIATE 'DROP INDEX RENDIMPC.IDX_RAP_SCARTI';
	END IF;
	
END;
