DECLARE

CURSOR SCARTI_RAPPORTI_NOGEST IS
	SELECT   TMP.ROWID, TMP.* 
	FROM TMP_PFRAP TMP
	WHERE TMP.TIPORAPPORTO = '96';

TYPE SCARTI_RAPPORTI_NOGEST_TYPE IS TABLE OF SCARTI_RAPPORTI_NOGEST%ROWTYPE INDEX BY PLS_INTEGER;

RES_SCARTI_RAPPORTI_NOGEST SCARTI_RAPPORTI_NOGEST_TYPE;

ROWS      PLS_INTEGER := 10000;
        
I 				NUMBER(38,0);
TOTALE			NUMBER(38,0):=0;
CHECK_IDX		NUMBER(38,0):=0;


BEGIN
	
	SELECT COUNT(*) INTO CHECK_IDX FROM user_indexes WHERE index_name = 'IDX_RAP_SCARTI';
	IF CHECK_IDX = 0 THEN
	    EXECUTE IMMEDIATE 'CREATE INDEX RENDIMPC.IDX_RAP_SCARTI ON TMP_PFRAP(NDG,CODICERAPPORTO,TIPORAPPORTO) TABLESPACE RENDIMPC_INDEX PARALLEL 8';
			EXECUTE IMMEDIATE 'ALTER INDEX IDX_RAP_SCARTI NOPARALLEL';
	END IF; 
	
	
	OPEN SCARTI_RAPPORTI_NOGEST;
	LOOP
			FETCH SCARTI_RAPPORTI_NOGEST BULK COLLECT INTO RES_SCARTI_RAPPORTI_NOGEST LIMIT ROWS;
				EXIT WHEN RES_SCARTI_RAPPORTI_NOGEST.COUNT = 0;  
				
	      I:=0;
	      I:= RES_SCARTI_RAPPORTI_NOGEST.COUNT;
	      TOTALE := TOTALE + I;
				
				FORALL J IN RES_SCARTI_RAPPORTI_NOGEST.FIRST .. RES_SCARTI_RAPPORTI_NOGEST.LAST		
	
				INSERT   INTO TBL_SCARTI_TMP_PFRAP (	CODICEAGENZIA,
														CODICEBANCA,
														CODICERAPPORTO,
														C_SOTTORAPPORTO,
														DT_APERTURA,
														DT_CHIUSURA,
														ID_BUONO_ORIGINARIO,
														NDG,
														NDG_SECONDARIO,
														PERIMETRO,
														STATO,
														TIPORAPPORTO,
														MOTIVO_SCARTO,
														TMSTP 
														)
												VALUES (RES_SCARTI_RAPPORTI_NOGEST(J).CODICEAGENZIA,
														RES_SCARTI_RAPPORTI_NOGEST(J).CODICEBANCA,
														RES_SCARTI_RAPPORTI_NOGEST(J).CODICERAPPORTO,
														RES_SCARTI_RAPPORTI_NOGEST(J).C_SOTTORAPPORTO,
														RES_SCARTI_RAPPORTI_NOGEST(J).DT_APERTURA,
														RES_SCARTI_RAPPORTI_NOGEST(J).DT_CHIUSURA,
														RES_SCARTI_RAPPORTI_NOGEST(J).ID_BUONO_ORIGINARIO,
														RES_SCARTI_RAPPORTI_NOGEST(J).NDG,
														RES_SCARTI_RAPPORTI_NOGEST(J).NDG_SECONDARIO,
														RES_SCARTI_RAPPORTI_NOGEST(J).PERIMETRO,
														RES_SCARTI_RAPPORTI_NOGEST(J).STATO,
														RES_SCARTI_RAPPORTI_NOGEST(J).TIPORAPPORTO,
														'COLONNA "TIPORAPPORTO=96" NON GESTITA',
														SYSDATE
														);
				
			        COMMIT;		
			        
			        FORALL J IN RES_SCARTI_RAPPORTI_NOGEST.FIRST .. RES_SCARTI_RAPPORTI_NOGEST.LAST
			        	
			        DELETE   FROM TMP_PFRAP TMP_DEL
					WHERE TMP_DEL.ROWID = RES_SCARTI_RAPPORTI_NOGEST(J).ROWID;
					
					COMMIT;
			        	
	            
	             INSERT INTO OUTPUT_PRINT_TABLE VALUES (TO_NUMBER(TO_CHAR(SYSDATE,'YYYYMMDDHH24MISS')) || ' SCARTI TMP_PFRAP PER COLONNA "TIPORAPPORTO=96" NON GESTITA: ' || I || ' RECORD');
			        
	END LOOP;
	CLOSE SCARTI_RAPPORTI_NOGEST;
	
	INSERT INTO OUTPUT_PRINT_TABLE VALUES (TO_NUMBER(TO_CHAR(SYSDATE,'YYYYMMDDHH24MISS')) || ' SCARTI TMP_PFRAP PER COLONNA "TIPORAPPORTO=96" NON GESTITA: ' || TOTALE);
	COMMIT;
	
	SELECT COUNT(*) INTO CHECK_IDX FROM user_indexes WHERE index_name = 'IDX_RAP_SCARTI';
	IF CHECK_IDX = 1 THEN
	    EXECUTE IMMEDIATE 'DROP INDEX RENDIMPC.IDX_RAP_SCARTI';
	END IF;
	
END;
