DECLARE i INTEGER;

BEGIN
	
SELECT COUNT(*) INTO i FROM user_indexes WHERE index_name = 'RAPP_NDGC_IDX';
IF i > 0 THEN
    EXECUTE IMMEDIATE 'DROP INDEX RENDIMPC.RAPP_NDGC_IDX';
END IF;


SELECT COUNT(*) INTO i FROM user_indexes WHERE index_name = 'RAPP_NDGC_STAT_IDX';
IF i > 0 THEN
    EXECUTE IMMEDIATE 'DROP INDEX RENDIMPC.RAPP_NDGC_STAT_IDX';
END IF;


SELECT COUNT(*) INTO i FROM user_constraints WHERE constraint_name = 'FK_SERIE_STORICA_SF';
IF i =1 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE RENDIMPC.SERIE_STORICA DROP CONSTRAINT FK_SERIE_STORICA_SF';
END IF;


SELECT COUNT(*) INTO i FROM user_constraints WHERE constraint_name = 'FK_SALDO_REND_PORTAFOGLIO';
IF i =1 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE RENDIMPC.SALDO_REND DISABLE CONSTRAINT FK_SALDO_REND_PORTAFOGLIO';
END IF;


SELECT COUNT(*) INTO i FROM user_constraints WHERE constraint_name = 'FK_SALDO_REND_STRUMENTOFINANZI';
IF i =1 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE RENDIMPC.SALDO_REND DISABLE CONSTRAINT FK_SALDO_REND_STRUMENTOFINANZI';
END IF;


SELECT COUNT(*) INTO i FROM user_constraints WHERE constraint_name = 'FK_MOVIMENTO_CODICETITOLO';
IF i =1 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE RENDIMPC.MOVIMENTO DISABLE CONSTRAINT FK_MOVIMENTO_CODICETITOLO';
END IF;

SELECT COUNT(*) INTO i FROM user_constraints WHERE constraint_name = 'FK_MOVIMENTO_TERZO_CODICE';
IF i =1 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE RENDIMPC.MOVIMENTO_RAMO_TERZO DISABLE CONSTRAINT FK_MOVIMENTO_TERZO_CODICE';
END IF;

SELECT COUNT(*) INTO i FROM user_constraints WHERE constraint_name = 'FK_COSTO_POS_SF';
IF i =1 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE RENDIMPC.COSTO_POSIZIONE DISABLE CONSTRAINT FK_COSTO_POS_SF';
END IF;

SELECT COUNT(*) INTO i FROM user_constraints WHERE constraint_name = 'SF_PK';
IF i =1 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE RENDIMPC.STRUMENTOFINANZIARIO DISABLE CONSTRAINT SF_PK';
END IF;


SELECT COUNT(*) INTO i FROM user_constraints WHERE constraint_name = 'RAPP_FK_IDPTF';
IF i =1 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE RENDIMPC.RAPPORTO DROP CONSTRAINT RAPP_FK_IDPTF';
END IF;


SELECT COUNT(*) INTO i FROM user_constraints WHERE constraint_name = 'RAPP_FK_NDG';
IF i =1 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE RENDIMPC.RAPPORTO DROP CONSTRAINT RAPP_FK_NDG';
END IF;


SELECT COUNT(*) INTO i FROM USER_INDEXES WHERE INDEX_NAME =  'IX_RAPP_FK_IDPTF';
IF i = 1 THEN
    EXECUTE IMMEDIATE 'DROP INDEX RENDIMPC.IX_RAPP_FK_IDPTF';
END IF;


--SELECT COUNT(*) INTO i FROM user_constraints WHERE constraint_name = 'NDG_PK';
--IF i =1 THEN
--   EXECUTE IMMEDIATE 'ALTER TABLE RENDIMPC.NDG DROP CONSTRAINT NDG_PK';
--END IF;


SELECT COUNT(*) INTO i FROM user_constraints WHERE constraint_name = 'TEMP_PROFILO_PK';
IF i > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE RENDIMPC.TEMP_PROFILO DROP CONSTRAINT TEMP_PROFILO_PK';
END IF;


SELECT COUNT(*) INTO i FROM user_constraints WHERE constraint_name = 'TEMP_CLIENTE_PK';
IF i > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE RENDIMPC.TEMP_CLIENTE DROP CONSTRAINT TEMP_CLIENTE_PK';
END IF;


SELECT COUNT(*) INTO i FROM user_constraints WHERE constraint_name = 'TEMP_RAPPORTO_PK';
IF i > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE RENDIMPC.TEMP_RAPPORTO DROP CONSTRAINT TEMP_RAPPORTO_PK';
END IF;


SELECT COUNT(*) INTO i FROM user_constraints WHERE constraint_name = 'TEMP_RAPPORTO_BFP_PK';
IF i > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE RENDIMPC.TEMP_RAPPORTO_BFP DROP CONSTRAINT TEMP_RAPPORTO_BFP_PK';
END IF;


SELECT COUNT(*) INTO i FROM user_constraints WHERE constraint_name = 'TEMP_DELTARAPPORTO_PK';
IF i > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE RENDIMPC.TEMP_DELTARAPPORTO DROP CONSTRAINT TEMP_DELTARAPPORTO_PK';
END IF;


SELECT COUNT(*) INTO i FROM USER_INDEXES WHERE INDEX_NAME =  'PTF_CODICE_IDX';
IF i > 0 THEN
    EXECUTE IMMEDIATE 'DROP INDEX RENDIMPC.PTF_CODICE_IDX';
END IF;


SELECT COUNT(*) INTO i FROM USER_INDEXES WHERE INDEX_NAME =  'PFRAP_NDG_IDX';
IF i > 0 THEN
    EXECUTE IMMEDIATE 'DROP INDEX RENDIMPC.PFRAP_NDG_IDX';
END IF;


SELECT COUNT(*) INTO i FROM USER_INDEXES WHERE INDEX_NAME =  'TEMP_PTF_CODICE_IDX';
IF i > 0 THEN
    EXECUTE IMMEDIATE 'DROP INDEX RENDIMPC.TEMP_PTF_CODICE_IDX';
END IF;


SELECT COUNT(*) INTO i FROM USER_INDEXES WHERE INDEX_NAME =  'TEMP_SALDI_IDX';
IF i > 0 THEN
    EXECUTE IMMEDIATE 'DROP INDEX RENDIMPC.TEMP_SALDI_IDX';
END IF;


SELECT COUNT(*) INTO i FROM USER_INDEXES WHERE INDEX_NAME =  'RAPP_TMPSAL_IDX';
IF i > 0 THEN
    EXECUTE IMMEDIATE 'DROP INDEX RENDIMPC.RAPP_TMPSAL_IDX';
END IF;


SELECT COUNT(*) INTO i FROM USER_INDEXES WHERE INDEX_NAME =  'TMP_GMPOL1_IDX';
IF i > 0 THEN
    EXECUTE IMMEDIATE 'DROP INDEX RENDIMPC.TMP_GMPOL1_IDX';
END IF;


SELECT COUNT(*) INTO i FROM USER_INDEXES WHERE INDEX_NAME =  'TMP_GMPOL2_IDX';
IF i > 0 THEN
    EXECUTE IMMEDIATE 'DROP INDEX RENDIMPC.TMP_GMPOL2_IDX';
END IF;


SELECT COUNT(*) INTO i FROM USER_INDEXES WHERE INDEX_NAME =  'TMP_RAMOPOL_IDX';
IF i > 0 THEN
    EXECUTE IMMEDIATE 'DROP INDEX RENDIMPC.TMP_RAMOPOL_IDX';
END IF;


SELECT COUNT(*) INTO i FROM USER_INDEXES WHERE INDEX_NAME =  'TMP_SALDOCODICETIT_IDX';
IF i > 0 THEN
    EXECUTE IMMEDIATE 'DROP INDEX RENDIMPC.TMP_SALDOCODICETIT_IDX';
END IF;


SELECT COUNT(*) INTO i FROM USER_INDEXES WHERE INDEX_NAME =  'TMP_IX_CLI_INT';
IF i > 0 THEN
    EXECUTE IMMEDIATE 'DROP INDEX RENDIMPC.TMP_IX_CLI_INT';
END IF;


SELECT COUNT(*) INTO i FROM USER_INDEXES WHERE INDEX_NAME =  'TMP_IX_PTFD_CLI';
IF i = 1 THEN
    EXECUTE IMMEDIATE 'DROP INDEX RENDIMPC.TMP_IX_PTFD_CLI';
END IF;


SELECT COUNT(*) INTO i FROM USER_INDEXES WHERE INDEX_NAME =  'TMP_IX_NDG_CLI';
IF i = 1 THEN
    EXECUTE IMMEDIATE 'DROP INDEX RENDIMPC.TMP_IX_NDG_CLI';
END IF;


SELECT COUNT(*) INTO i FROM USER_INDEXES WHERE INDEX_NAME =  'TMP_IX_NDGCLUSTER_TEMCLI';
IF i = 1 THEN
    EXECUTE IMMEDIATE 'DROP INDEX RENDIMPC.TMP_IX_NDGCLUSTER_TEMCLI';
END IF;


SELECT COUNT(*) INTO i FROM USER_INDEXES WHERE INDEX_NAME =  'TMP_IX_PRF_TEMPRF';
IF i = 1 THEN
    EXECUTE IMMEDIATE 'DROP INDEX RENDIMPC.TMP_IX_PRF_TEMPRF';
END IF;


SELECT COUNT(*) INTO i FROM USER_INDEXES WHERE INDEX_NAME =  'IX_RAPPORTO_PZ1';
IF i = 1 THEN
    EXECUTE IMMEDIATE 'DROP INDEX RENDIMPC.IX_RAPPORTO_PZ1';
END IF;


SELECT COUNT(*) INTO i FROM USER_INDEXES WHERE INDEX_NAME = 'TEMP_IDX_TMP_RAP';
IF i = 1 THEN
    EXECUTE IMMEDIATE 'DROP INDEX RENDIMPC.TEMP_IDX_TMP_RAP';
END IF;


SELECT COUNT(*) INTO i FROM USER_INDEXES WHERE INDEX_NAME = 'TEMP_RAP_IDX_TIPO';
IF i = 1 THEN
    EXECUTE IMMEDIATE 'DROP INDEX RENDIMPC.TEMP_RAP_IDX_TIPO';
END IF;


SELECT COUNT(*) INTO i FROM USER_INDEXES WHERE INDEX_NAME = 'TEMP_RAP_IDX_BUONO';
IF i = 1 THEN
    EXECUTE IMMEDIATE 'DROP INDEX RENDIMPC.TEMP_RAP_IDX_BUONO';
END IF;


SELECT COUNT(*) INTO i FROM USER_INDEXES WHERE INDEX_NAME = 'TEMP_RAP_IDX_MERGE_PZ';
IF i = 1 THEN
    EXECUTE IMMEDIATE 'DROP INDEX RENDIMPC.TEMP_RAP_IDX_MERGE_PZ';
END IF;


SELECT COUNT(*) INTO i FROM user_indexes WHERE index_name = 'TMP_IX_RAP_SOSP';
IF i = 1 THEN
	EXECUTE IMMEDIATE 'DROP INDEX TMP_IX_RAP_SOSP';
END IF;


SELECT COUNT(*) INTO i FROM user_indexes WHERE index_name = 'TMP_SAL_IDX_J';
IF i = 1 THEN
	EXECUTE IMMEDIATE 'DROP INDEX TMP_SAL_IDX_J';
END IF;
COMMIT;


SELECT COUNT(*) INTO i FROM user_indexes WHERE index_name = 'TEMP_RAP_IDX_DELTA';
IF i = 1 THEN
    EXECUTE IMMEDIATE 'DROP INDEX RENDIMPC.TEMP_RAP_IDX_DELTA';
END IF;

END;



