DECLARE
    i INTEGER;
BEGIN
    SELECT COUNT(*) INTO i FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'TEMP_CLIENTE_PK';
    IF i =0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE TEMP_CLIENTE ADD CONSTRAINT TEMP_CLIENTE_PK PRIMARY KEY (NDG) USING INDEX TABLESPACE RENDIMPC_INDEX';
        EXECUTE IMMEDIATE 'ALTER INDEX TEMP_CLIENTE_PK NOPARALLEL';
    END IF;
  dbms_stats.gather_table_stats(ownname => sys_context('USERENV', 'CURRENT_SCHEMA'), tabname => 'TEMP_CLIENTE', degree => 4, estimate_percent=>1);
END;