/**
*	INSERT NELLA TEMP_DELTA DEI RAPPORTI DA INSERIRE
*/
DECLARE
i INTEGER;
BEGIN

	INSERT /*+APPEND NOLOGGING PARALLEL(8)*/  INTO TEMP_DELTARAPPORTO (CODICEBANCA,CODICERAPPORTO,NDG,CODICEAGENZIA,TIPORAPPORTO,PERIMETRO,C_SOTTORAPPORTO,NDG_SECONDARIO,DT_APERTURA,DT_CHIUSURA,STATO,ID,IDPTF,ID_BUONO_ORIGINARIO)
 	SELECT CODICEBANCA,CODICERAPPORTO,NDG,CODICEAGENZIA,TIPORAPPORTO,PERIMETRO,C_SOTTORAPPORTO,NDG_SECONDARIO,DT_APERTURA,DT_CHIUSURA,STATO,ID_RAPPORTO_SEQ.nextval,ID_PTF_SEQ.nextval,ID_BUONO_ORIGINARIO FROM TEMP_RAPPORTO_BFP T
		WHERE NOT EXISTS (SELECT 1 FROM RAPPORTO R WHERE
								              R.NDG=T.NDG
								              AND R.ID_BUONO_ORIGINARIO=T.ID_BUONO_ORIGINARIO
								              AND R.TIPO=T.TIPORAPPORTO
								              AND R.ID_BUONO_ORIGINARIO IS NOT NULL);

	COMMIT;
	
	SELECT COUNT(*) INTO i FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'TEMP_DELTARAPPORTO_PK';
    IF i =0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE TEMP_DELTARAPPORTO ADD CONSTRAINT TEMP_DELTARAPPORTO_PK PRIMARY KEY (NDG,CODICERAPPORTO,CODICEAGENZIA,TIPORAPPORTO) USING INDEX TABLESPACE RENDIMPC_INDEX';
    END IF;
    
    SELECT COUNT(*) INTO i FROM user_indexes WHERE index_name = 'TEMP_RAP_IDX_DELTA';
	IF i = 1 THEN
	    EXECUTE IMMEDIATE 'DROP INDEX RENDIMPC.TEMP_RAP_IDX_DELTA';
	END IF;
	
END;
