   
TRUNCATE TABLE TEMP_CLIENTE DROP STORAGE;

--/
begin  dbms_stats.gather_table_stats(ownname => sys_context('USERENV', 'CURRENT_SCHEMA'), tabname => 'TMP_PFANANDG', degree => 4, estimate_percent=>1); end;
/

--/
DECLARE
	BEGIN
	INSERT /*+APPEND NOLOGGING PARALLEL(8)*/ INTO TEMP_CLIENTE (CODICEBANCA,NDG,CODICECLUSTER,CODICETOL,ETA,STATOCIVILE,PROFESSIONE,AREAGEOGRAFICA,CIAE,DESC_CIAE,PRIVACY,SEGMENTOPATRIMONIALE,
			CAMPAGNE,CONTATTATI,DIPENDENTI,CLIENTESTRANIERO,POSTEPAYEVOLUTION,TITOLARITA,PORTAFOGLIOGESTORE,AGENZIAANAGRAFICA,CODICESTRUTTURA,CODICETIPOLOGIASOGGETTO,
			DENOMINAZIONE,DATADINASCITA,LUOGODINASCITA,NOME,COGNOME,CODICEFISCALE,PARTITAIVA,SESSO,TIPOSOCIETA,CITTADINANZA,COMUNERESIDENZA,PROVINCIARESIDENZA,INDIRIZZORESIDENZA,
			NAZIONERESIDENZA,CODICE_GESTORE,TIPO_PORTAFOGLIO)

		SELECT CODICEBANCA,NDG,CODICECLUSTER,CODICETOL,ETA,STATOCIVILE,PROFESSIONE,AREAGEOGRAFICA,CIAE,DESC_CIAE,PRIVACY,SEGMENTOPATRIMONIALE,
			CAMPAGNE,CONTATTATI,DIPENDENTI,CLIENTESTRANIERO,POSTEPAYEVOLUTION,TITOLARITA,PORTAFOGLIOGESTORE,AGENZIAANAGRAFICA,CODICESTRUTTURA,CODICETIPOLOGIASOGGETTO,
			DENOMINAZIONE,CASE WHEN DATADINASCITA IS NULL THEN NULL ELSE replace(DATADINASCITA,'-') END,LUOGODINASCITA,NOME,COGNOME,CODICEFISCALE,PARTITAIVA,SESSO,TIPOSOCIETA,CITTADINANZA,COMUNERESIDENZA,PROVINCIARESIDENZA,INDIRIZZORESIDENZA,
			NAZIONERESIDENZA,CODICE_GESTORE,TIPO_PORTAFOGLIO
	FROM TMP_PFANANDG;
COMMIT;
END;
/

--/
DECLARE
    i INTEGER;
BEGIN
    SELECT COUNT(*) INTO i FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'TEMP_CLIENTE_PK';
    IF i =0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE TEMP_CLIENTE ADD CONSTRAINT TEMP_CLIENTE_PK PRIMARY KEY (NDG) USING INDEX TABLESPACE RENDIMPC_INDEX';
        EXECUTE IMMEDIATE 'ALTER INDEX TEMP_CLIENTE_PK NOPARALLEL';
    END IF;
END;
/

--/
begin  dbms_stats.gather_table_stats(ownname => sys_context('USERENV', 'CURRENT_SCHEMA'), tabname => 'TEMP_CLIENTE', degree => 4, estimate_percent=>1); end;
/