DECLARE
    i INTEGER;
BEGIN
    SELECT COUNT(*) INTO i FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'TEMP_RAPPORTO_PK';
    IF i =0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE TEMP_RAPPORTO ADD CONSTRAINT TEMP_RAPPORTO_PK PRIMARY KEY (NDG,CODICERAPPORTO,TIPORAPPORTO) USING INDEX TABLESPACE RENDIMPC_INDEX ';
        EXECUTE IMMEDIATE 'ALTER INDEX TEMP_RAPPORTO_PK NOPARALLEL';
    END IF;
    
    SELECT COUNT(*) INTO i FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'TEMP_RAPPORTO_BFP_PK';
    IF i =0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE TEMP_RAPPORTO_BFP ADD CONSTRAINT TEMP_RAPPORTO_BFP_PK PRIMARY KEY (NDG,ID_BUONO_ORIGINARIO,CODICEAGENZIA,TIPORAPPORTO) USING INDEX TABLESPACE RENDIMPC_INDEX ';
        EXECUTE IMMEDIATE 'ALTER INDEX TEMP_RAPPORTO_BFP_PK NOPARALLEL';
    END IF;

    dbms_stats.gather_table_stats(ownname => sys_context('USERENV', 'CURRENT_SCHEMA'), tabname => 'TEMP_RAPPORTO', degree => 4, estimate_percent=>1);
    dbms_stats.gather_table_stats(ownname => sys_context('USERENV', 'CURRENT_SCHEMA'), tabname => 'TEMP_RAPPORTO_BFP', degree => 4, estimate_percent=>1);
    
END;

