INSERT /*+APPEND NOLOGGING PARALLEL(8)*/ INTO TEMP_CLIENTE (CODICEBANCA, NDG, CODICECLUSTER, CODICETOL,
                                                                       ETA, STATOCIVILE, PROFESSIONE,
                                                                       AREAGEOGRAFICA, CIAE, DESC_CIAE, PRIVACY,
                                                                       SEGMENTOPATRIMONIALE,
                                                                       CAMPAGNE, CONTATTATI, DIPENDENTI,
                                                                       CLIENTESTRANIERO, POSTEPAYEVOLUTION,
                                                                       TITOLARITA, PORTAFOGLIOGESTORE,
                                                                       AGENZIAANAGRAFICA, CODICESTRUTTURA,
                                                                       CODICETIPOLOGIASOGGETTO,
                                                                       DENOMINAZIONE, DATADINASCITA, LUOGODINASCITA,
                                                                       NOME, COGNOME, CODICEFISCALE, PARTITAIVA,
                                                                       SESSO, TIPOSOCIETA, CITTADINANZA,
                                                                       COMUNERESIDENZA, PROVINCIARESIDENZA,
                                                                       INDIRIZZORESIDENZA,
                                                                       NAZIONERESIDENZA, CODICE_GESTORE,
                                                                       TIPO_PORTAFOGLIO)

SELECT CODICEBANCA,
         NDG,
         CODICECLUSTER,
         CODICETOL,
         ETA,
         STATOCIVILE,
         PROFESSIONE,
         AREAGEOGRAFICA,
         CIAE,
         DESC_CIAE,
         PRIVACY,
         SEGMENTOPATRIMONIALE,
         CAMPAGNE,
         CONTATTATI,
         DIPENDENTI,
         CLIENTESTRANIERO,
         POSTEPAYEVOLUTION,
         TITOLARITA,
         PORTAFOGLIOGESTORE,
         AGENZIAANAGRAFICA,
         CODICESTRUTTURA,
         CODICETIPOLOGIASOGGETTO,
         DENOMINAZIONE,
         CASE WHEN DATADINASCITA IS NULL THEN NULL ELSE replace(DATADINASCITA, '-') END,
         LUOGODINASCITA,
         NOME,
         COGNOME,
         CODICEFISCALE,
         PARTITAIVA,
         SESSO,
         TIPOSOCIETA,
         CITTADINANZA,
         COMUNERESIDENZA,
         PROVINCIARESIDENZA,
         INDIRIZZORESIDENZA,
         NAZIONERESIDENZA,
         CODICE_GESTORE,
         TIPO_PORTAFOGLIO
  FROM TMP_PFANANDG;
  