DECLARE
    i INTEGER;
BEGIN

	EXECUTE IMMEDIATE 'TRUNCATE TABLE TEMP_PROFILO DROP STORAGE';
	COMMIT;
	
	SELECT Count(*) INTO i FROM user_indexes WHERE  index_name = 'TMP_IX_NDGCLUSTER_TEMCLI';
    IF i = 0 THEN
      EXECUTE IMMEDIATE'CREATE UNIQUE INDEX TMP_IX_NDGCLUSTER_TEMCLI ON TEMP_CLIENTE(NDG,CODICECLUSTER) TABLESPACE RENDIMPC_INDEX PARALLEL 8';
			EXECUTE IMMEDIATE 'ALTER INDEX TMP_IX_NDGCLUSTER_TEMCLI NOPARALLEL';
	END IF;
	
	
	SELECT COUNT(*) INTO i FROM user_indexes WHERE index_name = 'TMP_IX_PRF_TEMPRF';
	IF i = 0 THEN
		EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX TMP_IX_PRF_TEMPRF ON TMP_PFRISCHIO(NDG,QUESTIONARIOATTIVO,RISCHIO,PROFILOESPCON) TABLESPACE RENDIMPC_INDEX PARALLEL 8';
			EXECUTE IMMEDIATE 'ALTER INDEX TMP_IX_PRF_TEMPRF NOPARALLEL';
	END IF;
	
	SELECT COUNT(*) INTO I FROM ALL_TAB_COLUMNS WHERE UPPER(TABLE_NAME)=UPPER('TEMP_PROFILO') AND COLUMN_NAME = 'SITFIN' AND OWNER='RENDIMPC';
	IF I = 0 THEN
		EXECUTE IMMEDIATE 'ALTER TABLE RENDIMPC.TEMP_PROFILO ADD SITFIN VARCHAR2(50)';
	END IF;		 

	dbms_stats.gather_table_stats(ownname => sys_context('USERENV', 'CURRENT_SCHEMA'), tabname => 'TMP_PFRISCHIO', degree => 4, estimate_percent=>1);
	dbms_stats.gather_table_stats(ownname => sys_context('USERENV', 'CURRENT_SCHEMA'), tabname => 'TEMP_CLIENTE', degree => 4, estimate_percent=>1);

	INSERT /*+APPEND NOLOGGING PARALLEL(8)*/ INTO TEMP_PROFILO
	(CODICEBANCA, NDG, RISCHIO, HP1, HP2, HP3, HP4, HP5, PROFILOESPCON, QUESTIONARIOATTIVO, DATASCADENZAQUESTIONARIO,
	 CONTATOREFREQUENZA, CONSULENZA, CODICECLASSIFICAZIONEMIFID,SITFIN)
	SELECT CODICEBANCA,
				 NDG,
				 RISCHIO,
				 HP1,
				 HP2,
				 HP3,
				 HP4,
				 HP5,
				 PROFILOESPCON,
				 QUESTIONARIOATTIVO,
				 DATASCADENZAQUESTIONARIO,
				 CONTATOREFREQUENZA,
				 CONSULENZA,
				 CODICECLASSIFICAZIONEMIFID,
				 SITFIN
	FROM TMP_PFRISCHIO T
	WHERE NOT EXISTS(SELECT 1
									 FROM TEMP_CLIENTE c
									 WHERE T.NDG = c.ndg
										 AND C.CODICECLUSTER in ('3', '4')
										 and T.QUESTIONARIOATTIVO = '0'
										 AND T.RISCHIO = '2'
										 AND T.PROFILOESPCON = '2');
	
	COMMIT;
	
	SELECT COUNT(*) INTO i FROM user_indexes WHERE index_name = 'TMP_IX_NDGCLUSTER_TEMCLI';
	IF i = 1 THEN
		EXECUTE IMMEDIATE 'DROP INDEX TMP_IX_NDGCLUSTER_TEMCLI';
	END IF;
	
	SELECT COUNT(*) INTO i FROM user_indexes WHERE index_name = 'TMP_IX_PRF_TEMPRF';
	IF i = 1 THEN
		EXECUTE IMMEDIATE 'DROP INDEX TMP_IX_PRF_TEMPRF';
	END IF;
	
	 SELECT COUNT(*) INTO i FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'TEMP_PROFILO_PK';
    IF i =0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE TEMP_PROFILO ADD CONSTRAINT TEMP_PROFILO_PK PRIMARY KEY (NDG) USING INDEX TABLESPACE RENDIMPC_INDEX ';
    END IF;
	
    dbms_stats.gather_table_stats(ownname => sys_context('USERENV', 'CURRENT_SCHEMA'), tabname => 'PROFILORISCHIO', degree => 4, estimate_percent=>1);
    dbms_stats.gather_table_stats(ownname => sys_context('USERENV', 'CURRENT_SCHEMA'), tabname => 'TEMP_PROFILO', degree => 4, estimate_percent=>1);
END; 
