TRUNCATE TABLE TEMP_RAPPORTO DROP STORAGE;

TRUNCATE TABLE TEMP_RAPPORTO_PZ_MERGE DROP STORAGE;

TRUNCATE TABLE TEMP_RAPPORTO_BFP DROP STORAGE;

TRUNCATE TABLE TEMP_DELTARAPPORTO DROP STORAGE;


--TUTTI I RAPPORTI SENZA ID BUONO ORIGINARIO e tiporapporto <>95 (libretti vincolati)
INSERT /*+APPEND NOLOGGING PARALLEL(8)*/ INTO TEMP_RAPPORTO (CODICEBANCA,CODICERAPPORTO,NDG,CODICEAGENZIA,TIPORAPPORTO,PERIMETRO,C_SOTTORAPPORTO,NDG_SECONDARIO,DT_APERTURA,DT_CHIUSURA,STATO)

SELECT CODICEBANCA,CODICERAPPORTO, NDG, CODICEAGENZIA, TIPORAPPORTO,  PERIMETRO, C_SOTTORAPPORTO, NDG_SECONDARIO, DT_APERTURA, DT_CHIUSURA, STATO
FROM TMP_PFRAP T
WHERE EXISTS (SELECT 1 FROM TEMP_CLIENTE C WHERE T.NDG=C.NDG)
AND ID_BUONO_ORIGINARIO IS NULL
AND TIPORAPPORTO <> '95';


--TUTTI I RAPPORTI SU CUI AGGIONARE NDG SENZA ID BUONO ORIGINARIO
INSERT /*+APPEND NOLOGGING PARALLEL(8)*/ INTO TEMP_RAPPORTO_PZ_MERGE (CODICEBANCA,CODICERAPPORTO,NDG,CODICEAGENZIA,TIPORAPPORTO,PERIMETRO,C_SOTTORAPPORTO,NDG_SECONDARIO,DT_APERTURA,DT_CHIUSURA,STATO)

SELECT CODICEBANCA,CODICERAPPORTO, NDG, CODICEAGENZIA, TIPORAPPORTO,  PERIMETRO, C_SOTTORAPPORTO, NDG_SECONDARIO, DT_APERTURA, DT_CHIUSURA, STATO
FROM TMP_PFRAP T
WHERE EXISTS (SELECT 1 FROM RAPPORTO R WHERE R.CODICERAPPORTO=T.CODICERAPPORTO AND R.TIPO=T.TIPORAPPORTO AND R.NDG<>T.NDG AND R.ID_BUONO_ORIGINARIO IS NULL)
AND EXISTS (SELECT 1 FROM TEMP_CLIENTE C WHERE T.NDG=C.NDG);


--TUTTI I RAPPORTI CON ID BUONO ORIGINARIO
INSERT /*+APPEND NOLOGGING PARALLEL(8)*/ INTO TEMP_RAPPORTO_BFP (CODICEBANCA,CODICERAPPORTO,NDG,CODICEAGENZIA,TIPORAPPORTO,PERIMETRO,C_SOTTORAPPORTO,NDG_SECONDARIO,DT_APERTURA,DT_CHIUSURA,STATO,ID_BUONO_ORIGINARIO)

SELECT CODICEBANCA,CODICERAPPORTO, NDG, CODICEAGENZIA, TIPORAPPORTO,  PERIMETRO, C_SOTTORAPPORTO, NDG_SECONDARIO, DT_APERTURA, DT_CHIUSURA, STATO,ID_BUONO_ORIGINARIO
FROM TMP_PFRAP T
WHERE EXISTS (SELECT 1 FROM TEMP_CLIENTE C WHERE T.NDG=C.NDG)
AND ID_BUONO_ORIGINARIO IS NOT NULL;
