DECLARE 

	CNT				NUMBER(38,0):=0;
	CNT_SP			NUMBER(38,0):=0;

BEGIN
	
    SELECT COUNT(*) INTO CNT FROM tmp_pfsaldi_polizze;
    SELECT COUNT(*) INTO CNT_SP FROM tmp_pfsaldi_polizze_sp;

	IF (CNT >= 1000000 OR CNT_SP >= 1000000) THEN
	
		EXECUTE IMMEDIATE 'ALTER TABLE RENDIMPC.SALDO_REND NOLOGGING';
		EXECUTE IMMEDIATE 'ALTER TABLE RENDIMPC.SALDO_REND DISABLE CONSTRAINT FK_SALDO_REND_PORTAFOGLIO';
		EXECUTE IMMEDIATE 'ALTER TABLE RENDIMPC.SALDO_REND DISABLE CONSTRAINT FK_SALDO_REND_STRUMENTOFINANZI';
	    EXECUTE IMMEDIATE 'ALTER INDEX RENDIMPC.IDX_SALDO_REND_PK NOLOGGING';
	    
	END IF;

END;