DECLARE

CNT NUMBER := 0;

BEGIN
	
SELECT COUNT(*) INTO CNT FROM TMP_PFSALPOSP_RECUP;

IF (CNT >= 1000000) THEN

	EXECUTE IMMEDIATE 'ALTER TABLE RENDIMPC.SALDO_REND NOLOGGING';
	EXECUTE IMMEDIATE 'ALTER TABLE RENDIMPC.SALDO_REND DISABLE CONSTRAINT FK_SALDO_REND_PORTAFOGLIO';
	EXECUTE IMMEDIATE 'ALTER TABLE RENDIMPC.SALDO_REND DISABLE CONSTRAINT FK_SALDO_REND_STRUMENTOFINANZI';
	EXECUTE IMMEDIATE 'ALTER INDEX RENDIMPC.IDX_SALDO_REND_PK NOLOGGING';
        
END IF;

END;