DECLARE
CURSOR SCARTI_CAUSALI_DOPPIE IS
SELECT   TMP.ROWID, TMP.* 
FROM TMP_PFCAUSALI TMP
INNER JOIN (SELECT CODICECAUSALE, TIPORAPPORTO
	  FROM TMP_PFCAUSALI TMP
	  GROUP BY CODICECAUSALE, TIPORAPPORTO
	  HAVING COUNT(*) >1) A
ON TMP.CODICECAUSALE = A.CODICECAUSALE
AND TMP.TIPORAPPORTO=A.TIPORAPPORTO;

	TYPE SCARTI_CAUSALI_DOPPIE_TYPE IS TABLE OF SCARTI_CAUSALI_DOPPIE%ROWTYPE INDEX BY PLS_INTEGER;
	
	RES_SCARTI_CAUSALI_DOPPIE SCARTI_CAUSALI_DOPPIE_TYPE;
	
	ROWS      PLS_INTEGER := 10000;
	        
	I 				NUMBER(38,0);
	TOTALE			NUMBER(38,0):=0;
	
	BEGIN
	
	 
	
	
	
	OPEN SCARTI_CAUSALI_DOPPIE;
	LOOP
			FETCH SCARTI_CAUSALI_DOPPIE BULK COLLECT INTO RES_SCARTI_CAUSALI_DOPPIE LIMIT ROWS;
				EXIT WHEN RES_SCARTI_CAUSALI_DOPPIE.COUNT = 0;  
				
	      I:=0;
	      I:= RES_SCARTI_CAUSALI_DOPPIE.COUNT;
	      TOTALE := TOTALE + I;
				
				FORALL J IN RES_SCARTI_CAUSALI_DOPPIE.FIRST .. RES_SCARTI_CAUSALI_DOPPIE.LAST		
	
				INSERT   INTO TBL_SCARTI_TMP_PFCAUSALI (	CODICEBANCA,     
														CODICECAUSALE,   
														DESCRIZIONE,     
														TIPOLOGIACAUSALE,
														TIPORAPPORTO,    
														TMSTP,         
														MOTIVO_SCARTO,   
														RIPROPONIBILE   
														)
												VALUES (RES_SCARTI_CAUSALI_DOPPIE(J).CODICEBANCA,     
														RES_SCARTI_CAUSALI_DOPPIE(J).CODICECAUSALE,   
														RES_SCARTI_CAUSALI_DOPPIE(J).DESCRIZIONE,     
														RES_SCARTI_CAUSALI_DOPPIE(J).TIPOLOGIACAUSALE,
														RES_SCARTI_CAUSALI_DOPPIE(J).TIPORAPPORTO,    
														SYSDATE,           
														'CHIAVE PRIMARIA "CODICECAUSALE, TIPORAPPORTO" DUPLICATA',   
														'N'
														);
				
			        COMMIT;		
			        
			        FORALL J IN RES_SCARTI_CAUSALI_DOPPIE.FIRST .. RES_SCARTI_CAUSALI_DOPPIE.LAST
			        	
			        DELETE   FROM TMP_PFCAUSALI TMP_DEL
					WHERE TMP_DEL.ROWID = RES_SCARTI_CAUSALI_DOPPIE(J).ROWID;
					
					COMMIT;
			        	
	            
	             INSERT INTO OUTPUT_PRINT_TABLE VALUES (TO_NUMBER(TO_CHAR(SYSDATE,'YYYYMMDDHH24MISS')) || ' SCARTI TMP_PFCAUSALI PER CHIAVE (CODICECAUSALE, TIPORAPPORTO) DUPLICATA: ' || I || ' RECORD');
			        
	END LOOP;
	CLOSE SCARTI_CAUSALI_DOPPIE;
	
	INSERT INTO OUTPUT_PRINT_TABLE VALUES (TO_NUMBER(TO_CHAR(SYSDATE,'YYYYMMDDHH24MISS')) || ' SCARTI TMP_PFCAUSALI PER CHIAVE (CODICECAUSALE, TIPORAPPORTO) DUPLICATA: ' || TOTALE);
	COMMIT;
END;