BEGIN
   
	
	
END;

DECLARE

CURSOR DEL_CUR IS
SELECT    SCARTO.ROWID AS SCARTO_ROWID, SCARTO.*, TMP.ROWID AS TMP_ROWID
FROM TBL_SCARTI_TMP_PFMOVIMENTI SCARTO
LEFT JOIN TMP_PFMOVIMENTI TMP
	ON TMP.CODICE = SCARTO.CODICE
	AND TMP.CODICEINTERNO = SCARTO.CODICEINTERNO
	AND TMP.CODICERAPPORTO = SCARTO.CODICERAPPORTO
WHERE SCARTO.RIPROPONIBILE = 'S';

I 				NUMBER(38,0):=0;
REUSE_COUNT		NUMBER(38,0):=0;	


BEGIN
	
	FOR CUR_ITEM IN DEL_CUR 

		LOOP
			
		I := I+1;
		
		IF(CUR_ITEM.TMP_ROWID IS NULL) THEN
		
		INSERT    INTO TMP_PFMOVIMENTI (	CODICEBANCA,
										CODICE,
										CODICEAGENZIA,
										CODICERAPPORTO,
										TIPORAPPORTO,
										CODICEINTERNO,
										CAUSALE,
										CTVREGOLATO,
										CTVMERCATO,
										CTVREGOLATODIVISA,
										CTVMERCATODIVISA,
										DIVISA,
										QUANTITA,
										PREZZOMERCATO,
										PREZZO,
										RATEOLORDO,
										RATEONETTO,
										CAMBIO,
										DATAORDINE,
										DATACONTABILE,
										DATAVALUTA,
										FLAGSTORNO,
										CODICESTORNO,
										FLAGCANCELLATO,
										IMPOSTE,
										COMMISSIONI,
										DATAAGGIORNAMENTO
									)
								VALUES (CUR_ITEM.CODICEBANCA,
										CUR_ITEM.CODICE,
										CUR_ITEM.CODICEAGENZIA,
										CUR_ITEM.CODICERAPPORTO,
										CUR_ITEM.TIPORAPPORTO,
										CUR_ITEM.CODICEINTERNO,
										CUR_ITEM.CAUSALE,
										CUR_ITEM.CTVREGOLATO,
										CUR_ITEM.CTVMERCATO,
										CUR_ITEM.CTVREGOLATODIVISA,
										CUR_ITEM.CTVMERCATODIVISA,
										CUR_ITEM.DIVISA,
										CUR_ITEM.QUANTITA,
										CUR_ITEM.PREZZOMERCATO,
										CUR_ITEM.PREZZO,
										CUR_ITEM.RATEOLORDO,
										CUR_ITEM.RATEONETTO,
										CUR_ITEM.CAMBIO,
										CUR_ITEM.DATAORDINE,
										CUR_ITEM.DATACONTABILE,
										CUR_ITEM.DATAVALUTA,
										CUR_ITEM.FLAGSTORNO,
										CUR_ITEM.CODICESTORNO,
										CUR_ITEM.FLAGCANCELLATO,
										CUR_ITEM.IMPOSTE,
										CUR_ITEM.COMMISSIONI,
										CUR_ITEM.DATAAGGIORNAMENTO
										);
										
				REUSE_COUNT := REUSE_COUNT + 1;			
				
			END IF;		
			
			DELETE    FROM TBL_SCARTI_TMP_PFMOVIMENTI TBL
			WHERE TBL.ROWID = CUR_ITEM.SCARTO_ROWID;
						
		IF MOD(I,10000) = 0 THEN
			INSERT INTO OUTPUT_PRINT_TABLE VALUES (TO_NUMBER(TO_CHAR(SYSDATE,'YYYYMMDDHH24MISS')) || ' REUSE SCARTI TMP_PFMOVIMENTI. COMMIT ON ROW: ' || I);
			COMMIT;
		END IF;

		END LOOP;
			INSERT INTO OUTPUT_PRINT_TABLE VALUES (TO_NUMBER(TO_CHAR(SYSDATE,'YYYYMMDDHH24MISS')) || ' REUSE SCARTI TMP_PFMOVIMENTI. RECORD RECUPERATI: ' || REUSE_COUNT);
		COMMIT;

END;