BEGIN
   
	
	
END;

DECLARE
CURSOR SCARTI_MOVIMENTI_FONDI IS
SELECT   TMP.ROWID, TMP.* 
FROM TMP_PFMOV_FONDI TMP
INNER JOIN (SELECT CODICE, CODICEINTERNO, CODICERAPPORTO
	  FROM TMP_PFMOV_FONDI TMP
	  GROUP BY CODICE, CODICEINTERNO, CODICERAPPORTO
	  HAVING COUNT(*) >1) A
ON TMP.CODICE = A.CODICE
AND TMP.CODICEINTERNO=A.CODICEINTERNO
AND TMP.CODICERAPPORTO = A.CODICERAPPORTO;


	TYPE SCARTI_MOVIMENTI_FONDI_TYPE IS TABLE OF SCARTI_MOVIMENTI_FONDI%ROWTYPE INDEX BY PLS_INTEGER;
	
	RES_SCARTI_MOVIMENTI_FONDI SCARTI_MOVIMENTI_FONDI_TYPE;
	
	ROWS      PLS_INTEGER := 10000;
	        
	I 			NUMBER(38,0);
	TOTALE			NUMBER(38,0):=0;
	
	BEGIN
	
		
	OPEN SCARTI_MOVIMENTI_FONDI;
	LOOP
			FETCH SCARTI_MOVIMENTI_FONDI BULK COLLECT INTO RES_SCARTI_MOVIMENTI_FONDI LIMIT ROWS;
				EXIT WHEN RES_SCARTI_MOVIMENTI_FONDI.COUNT = 0;  
				
	      I:=0;
	      I:= RES_SCARTI_MOVIMENTI_FONDI.COUNT;
	      TOTALE := TOTALE + I;
				
				FORALL J IN RES_SCARTI_MOVIMENTI_FONDI.FIRST .. RES_SCARTI_MOVIMENTI_FONDI.LAST		
	
				INSERT   INTO TBL_SCARTI_TMP_PFMOV_FONDI (	CODICEBANCA,       
															CODICE,            
															CODICEAGENZIA,    
															CODICERAPPORTO,    
															TIPORAPPORTO,      
															CODICEINTERNO,     
															CAUSALE,           
															CTVREGOLATO,       
															CTVMERCATO,        
															CTVREGOLATODIVISA, 
															CTVMERCATODIVISA,  
															DIVISA,            
															QUANTITA,          
															PREZZOMERCATO,    
															PREZZO,            
															RATEOLORDO,       
															RATEONETTO,        
															CAMBIO,            
															DATAORDINE,        
															DATACONTABILE,     
															DATAVALUTA,     
															FLAGSTORNO,        
															CODICESTORNO,      
															FLAGCANCELLATO,    
															IMPOSTE,           
															COMMISSIONI,       
															DATAAGGIORNAMENTO, 
															TMSTP,             
															MOTIVO_SCARTO,     
															RIPROPONIBILE
														)
												VALUES (RES_SCARTI_MOVIMENTI_FONDI(J).CODICEBANCA,       
														RES_SCARTI_MOVIMENTI_FONDI(J).CODICE,            
														RES_SCARTI_MOVIMENTI_FONDI(J).CODICEAGENZIA,    
														RES_SCARTI_MOVIMENTI_FONDI(J).CODICERAPPORTO,    
														RES_SCARTI_MOVIMENTI_FONDI(J).TIPORAPPORTO,      
														RES_SCARTI_MOVIMENTI_FONDI(J).CODICEINTERNO,     
														RES_SCARTI_MOVIMENTI_FONDI(J).CAUSALE,           
														RES_SCARTI_MOVIMENTI_FONDI(J).CTVREGOLATO,       
														RES_SCARTI_MOVIMENTI_FONDI(J).CTVMERCATO,        
														RES_SCARTI_MOVIMENTI_FONDI(J).CTVREGOLATODIVISA, 
														RES_SCARTI_MOVIMENTI_FONDI(J).CTVMERCATODIVISA,  
														RES_SCARTI_MOVIMENTI_FONDI(J).DIVISA,            
														RES_SCARTI_MOVIMENTI_FONDI(J).QUANTITA,          
														RES_SCARTI_MOVIMENTI_FONDI(J).PREZZOMERCATO,    
														RES_SCARTI_MOVIMENTI_FONDI(J).PREZZO,            
														RES_SCARTI_MOVIMENTI_FONDI(J).RATEOLORDO,       
														RES_SCARTI_MOVIMENTI_FONDI(J).RATEONETTO,        
														RES_SCARTI_MOVIMENTI_FONDI(J).CAMBIO,            
														RES_SCARTI_MOVIMENTI_FONDI(J).DATAORDINE,        
														RES_SCARTI_MOVIMENTI_FONDI(J).DATACONTABILE,     
														RES_SCARTI_MOVIMENTI_FONDI(J).DATAVALUTA,     
														RES_SCARTI_MOVIMENTI_FONDI(J).FLAGSTORNO,        
														RES_SCARTI_MOVIMENTI_FONDI(J).CODICESTORNO,      
														RES_SCARTI_MOVIMENTI_FONDI(J).FLAGCANCELLATO,    
														RES_SCARTI_MOVIMENTI_FONDI(J).IMPOSTE,           
														RES_SCARTI_MOVIMENTI_FONDI(J).COMMISSIONI,       
														RES_SCARTI_MOVIMENTI_FONDI(J).DATAAGGIORNAMENTO,
														SYSDATE,
														'CHIAVE PRIMARIA "CODICE, CODICEINTERNO, CODICERAPPORTO" DUPLICATA',
														'N'
														);
				
			        COMMIT;		
			        
			        FORALL J IN RES_SCARTI_MOVIMENTI_FONDI.FIRST .. RES_SCARTI_MOVIMENTI_FONDI.LAST
			        	
			        DELETE   FROM TMP_PFMOV_FONDI TMP_DEL
					WHERE TMP_DEL.ROWID = RES_SCARTI_MOVIMENTI_FONDI(J).ROWID;
					
					COMMIT;
			        	
	            
	             INSERT INTO OUTPUT_PRINT_TABLE VALUES (TO_NUMBER(TO_CHAR(SYSDATE,'YYYYMMDDHH24MISS')) || ' SCARTI  TMP_PFMOV_FONDI PER CHIAVE (CODICE, CODICEINTERNO, CODICERAPPORTO) DUPLICATA: ' || I || ' RECORD');
			        
	END LOOP;
	CLOSE SCARTI_MOVIMENTI_FONDI;
	
	INSERT INTO OUTPUT_PRINT_TABLE VALUES (TO_NUMBER(TO_CHAR(SYSDATE,'YYYYMMDDHH24MISS')) || ' SCARTI  TMP_PFMOV_FONDI PER CHIAVE (CODICE, CODICEINTERNO, CODICERAPPORTO) DUPLICATA: ' || TOTALE);
	COMMIT;
END;